import { APP_ROUTES } from "@/lib/app-routes";

import type { DashboardSeedData } from "./dashboard-types";

export const DASHBOARD_SEED_DATA: DashboardSeedData = {
  facility: {
    id: "facility-spm-01-north-block",
    name: "SPM-01 Instalasi Stasiun Pengumpul Minyak — North Block Gathering Station",
    shortName: "SPM-01 North Block Gathering Station",
    type: "Upstream oil and gas gathering station",
    owner: "SUCOFINDO — Asset Integrity & RBI Services",
    nominalThroughput: [
      "22,000 BOPD gross liquid handling capacity",
      "16,500 BOPD crude export",
      "18 MMSCFD associated gas",
      "14,000 BWPD produced-water handling",
      "6,500 bbl onsite storage",
    ],
    operatingMode: [
      "Continuous 24/7 brownfield operation",
      "Mid-life facility",
      "Mixed legacy documentation",
      "Ongoing RBI baseline implementation",
      "Active inspection/certification renewal campaign",
    ],
    userContext: "Frido Satrio — SUCOFINDO — Superadmin",
    footerDateLabel: "Jumat, 12 Juni 2026",
  },
  assetClasses: [
    { id: "pressure-vessels", label: "Pressure vessels", count: 11, iconLabel: "PV" },
    { id: "heat-exchangers", label: "Heater treaters / heat exchangers", count: 7, iconLabel: "HX" },
    { id: "tanks", label: "Tanks, sumps, closed drains, and storage vessels", count: 13, iconLabel: "TK" },
    { id: "pumps", label: "Pumps", count: 22, iconLabel: "P" },
    { id: "compressors", label: "Compressors and blowers", count: 5, iconLabel: "C" },
    { id: "piping-circuits", label: "Piping circuits and flowlines", count: 31, iconLabel: "PL" },
    { id: "pressure-safety-devices", label: "Pressure safety devices", count: 17, iconLabel: "PSV" },
    { id: "metering-skids", label: "Metering, pigging, and custody-transfer skids", count: 8, iconLabel: "MTR" },
    { id: "esd-valves", label: "ESD/SDV and critical isolation valve assemblies", count: 10, iconLabel: "SDV" },
    { id: "critical-packages", label: "Instrumented, electrical, utility, package, and safety-critical assets", count: 18, iconLabel: "U" },
  ],
  riskMatrix: [
    { likelihood: 5, consequence: 1, count: 5, level: "medium" },
    { likelihood: 5, consequence: 2, count: 8, level: "medium-high" },
    { likelihood: 5, consequence: 3, count: 3, level: "high" },
    { likelihood: 5, consequence: 4, count: 4, level: "high" },
    { likelihood: 5, consequence: 5, count: 2, level: "high" },
    { likelihood: 4, consequence: 1, count: 5, level: "medium" },
    { likelihood: 4, consequence: 2, count: 6, level: "medium" },
    { likelihood: 4, consequence: 3, count: 9, level: "medium-high" },
    { likelihood: 4, consequence: 4, count: 3, level: "high" },
    { likelihood: 4, consequence: 5, count: 2, level: "high" },
    { likelihood: 3, consequence: 1, count: 4, level: "low" },
    { likelihood: 3, consequence: 2, count: 9, level: "medium" },
    { likelihood: 3, consequence: 3, count: 10, level: "medium-high" },
    { likelihood: 3, consequence: 4, count: 9, level: "medium-high" },
    { likelihood: 3, consequence: 5, count: 1, level: "high" },
    { likelihood: 2, consequence: 1, count: 7, level: "low" },
    { likelihood: 2, consequence: 2, count: 12, level: "medium" },
    { likelihood: 2, consequence: 3, count: 10, level: "medium" },
    { likelihood: 2, consequence: 4, count: 5, level: "medium" },
    { likelihood: 2, consequence: 5, count: 7, level: "medium-high" },
    { likelihood: 1, consequence: 1, count: 9, level: "low" },
    { likelihood: 1, consequence: 2, count: 5, level: "low" },
    { likelihood: 1, consequence: 3, count: 3, level: "low" },
    { likelihood: 1, consequence: 4, count: 3, level: "medium" },
    { likelihood: 1, consequence: 5, count: 1, level: "medium" },
  ],
  inspectionTrend: [
    { id: "jan-2026", label: "Jan '26", statuses: { overdue: 14, "due-30": 8, "due-90": 25, current: 60, "pending-validation": 15 } },
    { id: "feb-2026", label: "Feb '26", statuses: { overdue: 16, "due-30": 9, "due-90": 27, current: 58, "pending-validation": 16 } },
    { id: "mar-2026", label: "Mar '26", statuses: { overdue: 18, "due-30": 8, "due-90": 29, current: 55, "pending-validation": 18 } },
    { id: "apr-2026", label: "Apr '26", statuses: { overdue: 20, "due-30": 11, "due-90": 30, current: 53, "pending-validation": 20 } },
    { id: "may-2026", label: "May '26", statuses: { overdue: 18, "due-30": 10, "due-90": 29, current: 54, "pending-validation": 21 } },
    { id: "jun-2026", label: "Jun '26", statuses: { overdue: 19, "due-30": 9, "due-90": 31, current: 52, "pending-validation": 22 } },
  ],
  certificates: [
    {
      id: "cert-v-101-api510",
      assetId: "asset-v-101",
      assetTag: "V-101",
      assetName: "Inlet Separator",
      certificateType: "API 510-style inspection certificate",
      expiryDate: "May 26, 2026",
      daysLeft: -17,
      status: "expired",
      route: APP_ROUTES.certification.register,
    },
    {
      id: "cert-psv-1203-set-pressure",
      assetId: "asset-psv-1203",
      assetTag: "PSV-1203",
      assetName: "Pressure Safety Valve",
      certificateType: "Set pressure certificate",
      expiryDate: "Jun 10, 2026",
      daysLeft: -2,
      status: "expired",
      route: APP_ROUTES.certification.register,
    },
    {
      id: "cert-psv-1204-set-pressure",
      assetId: "asset-psv-1204",
      assetTag: "PSV-1204",
      assetName: "Pressure Safety Valve",
      certificateType: "Set pressure certificate",
      expiryDate: "Jun 25, 2026",
      daysLeft: 13,
      status: "due-soon",
      route: APP_ROUTES.certification.register,
    },
    {
      id: "cert-v-103-api510",
      assetId: "asset-v-103",
      assetTag: "V-103",
      assetName: "HP Separator",
      certificateType: "API 510-style inspection certificate",
      expiryDate: "Jul 05, 2026",
      daysLeft: 23,
      status: "due-soon",
      route: APP_ROUTES.certification.register,
    },
    {
      id: "cert-tk-301-api653",
      assetId: "asset-tk-301",
      assetTag: "TK-301",
      assetName: "Crude Storage Tank",
      certificateType: "API 653-style storage tank inspection",
      expiryDate: "Aug 18, 2026",
      daysLeft: 67,
      status: "due",
      route: APP_ROUTES.certification.register,
    },
  ],
  certificateSummary: {
    dueWithin180Days: 11,
    expiredOrUrgentEvidence: 4,
  },
  anomalyDistribution: [
    { severity: "critical", count: 5 },
    { severity: "high", count: 8 },
    { severity: "medium", count: 10 },
    { severity: "low", count: 6 },
  ],
  anomalySummary: {
    overdueCorrectiveActions: 8,
    waitingClientClarification: 14,
  },
  rbiProgress: [
    { id: "pressure-vessels", equipmentClass: "Pressure Vessels", assessed: 9, total: 11, methodologyLabel: "API 580-style RBI" },
    { id: "piping-circuits", equipmentClass: "Piping Circuits", assessed: 18, total: 31, methodologyLabel: "API 570-style piping inspection" },
    { id: "tanks", equipmentClass: "Tanks", assessed: 7, total: 13, methodologyLabel: "API 653-style storage tank inspection" },
    { id: "prds", equipmentClass: "PRDs / PSV / PRV", assessed: 10, total: 17, methodologyLabel: "API 581-style RBI analytics" },
    { id: "heat-exchangers", equipmentClass: "Heat Exchangers", assessed: 5, total: 7, methodologyLabel: "API 580-style RBI" },
  ],
  documentCompleteness: [
    { status: "complete", label: "Complete", count: 91 },
    { status: "partial", label: "Partial / Needs Update", count: 33 },
    { status: "missing", label: "Missing / Expired / Unvalidated", count: 18 },
  ],
  documentIssues: [
    {
      id: "doc-psv-packages",
      label: "PSV calibration packages incomplete",
      count: 6,
      status: "action-required",
      route: APP_ROUTES.documents.evidenceBuilder,
    },
    {
      id: "doc-pv-certificate-evidence",
      label: "Pressure vessels require certificate evidence update",
      count: 3,
      status: "action-required",
      route: APP_ROUTES.certification.register,
    },
    {
      id: "doc-tank-external-inspection",
      label: "Tanks require external inspection evidence completion",
      count: 2,
      status: "action-required",
      route: APP_ROUTES.documents.evidenceBuilder,
    },
  ],
  criticalAttention: [
    {
      id: "crit-v-101-expired-cert",
      assetId: "asset-v-101",
      assetTag: "V-101",
      assetName: "Inlet Separator",
      issue: "Expired inspection certificate",
      severity: "high",
      status: "open",
      dueStatus: "Overdue 17 days",
      relatedRoute: APP_ROUTES.anomalies.register,
      taxonomyLabels: ["Expired inspection certificate", "API 510-style pressure vessel inspection", "Inspection certification evidence"],
      recommendedAction: "Upload renewed certificate evidence or open renewal exception for SUCOFINDO technical review.",
    },
    {
      id: "crit-psv-1203-set-pressure",
      assetId: "asset-psv-1203",
      assetTag: "PSV-1203",
      assetName: "Pressure Safety Valve",
      issue: "Set-pressure documentation mismatch",
      severity: "high",
      status: "open",
      dueStatus: "Evidence incomplete",
      relatedRoute: APP_ROUTES.certification.register,
      taxonomyLabels: ["PSV set-pressure documentation mismatch", "Missing calibration evidence", "Regulatory matrix"],
      recommendedAction: "Reconcile PSV datasheet, calibration certificate, and renewal evidence before close-out.",
    },
    {
      id: "crit-cir-pw-05-mic",
      assetId: "asset-cir-pw-05",
      assetTag: "CIR-PW-05",
      assetName: "Produced Water Circuit",
      issue: "MIC screening & NDT validation overdue",
      severity: "medium-high",
      status: "open",
      dueStatus: "Overdue 9 days",
      relatedRoute: APP_ROUTES.inspections.findings,
      taxonomyLabels: ["MIC in stagnant produced-water lines", "Overdue NDT report validation", "MOC/IOW trigger review"],
      recommendedAction: "Confirm MIC screening scope and validate latest UT/NDT report before RBI baseline freeze.",
    },
    {
      id: "crit-c-501-vibration-fatigue",
      assetId: "asset-c-501-discharge-line",
      assetTag: "C-501 Gas Compressor discharge line",
      assetName: "Compressor Discharge Piping",
      issue: "Vibration fatigue concern",
      severity: "high",
      status: "open",
      dueStatus: "Overdue 6 days",
      relatedRoute: APP_ROUTES.rbi.riskRegister,
      taxonomyLabels: ["Vibration fatigue on compressor discharge piping", "Erosion-corrosion at high-velocity elbows", "Audit trail"],
      recommendedAction: "Escalate vibration survey evidence and review fatigue-sensitive CML/TML locations.",
    },
    {
      id: "crit-tk-302-external-evidence",
      assetId: "asset-tk-302",
      assetTag: "TK-302",
      assetName: "Produced Water Tank",
      issue: "External inspection evidence incomplete",
      severity: "medium-high",
      status: "waiting-validation",
      dueStatus: "Evidence incomplete",
      relatedRoute: APP_ROUTES.documents.evidenceBuilder,
      taxonomyLabels: ["External atmospheric corrosion", "Nozzle coating breakdown", "Document control"],
      recommendedAction: "Validate external inspection photo log, thickness summary, and inspector sign-off package.",
    },
    {
      id: "crit-sdv-701-calibration",
      assetId: "asset-sdv-701",
      assetTag: "SDV-701",
      assetName: "Critical Isolation Valve Assembly",
      issue: "Missing calibration evidence",
      severity: "medium",
      status: "due-soon",
      dueStatus: "Due in 8 days",
      relatedRoute: APP_ROUTES.certification.renewals,
      taxonomyLabels: ["Missing calibration evidence", "SUCOFINDO technical governance", "Audit trail"],
      recommendedAction: "Attach calibration certificate and verify approval workflow owner before due date.",
    },
  ],
  recommendationSummary: {
    open: 37,
    waitingClientClarification: 14,
  },
  integrityReadiness: {
    score: 74,
    target: 80,
    deltaLast30Days: 6,
  },
  taxonomyLabels: [
    "Internal CO2 corrosion",
    "H2S-related susceptibility screening",
    "Localized pitting",
    "Under-deposit corrosion",
    "External atmospheric corrosion",
    "Corrosion under insulation",
    "MIC in stagnant produced-water lines",
    "Erosion-corrosion at high-velocity elbows",
    "Vibration fatigue on compressor discharge piping",
    "Flange leakage",
    "Gasket degradation",
    "Nozzle coating breakdown",
    "Thinning at CML/TML locations",
    "PSV set-pressure documentation mismatch",
    "Missing calibration evidence",
    "Expired inspection certificate",
    "Incomplete P&ID revision control",
    "Overdue NDT report validation",
    "ISO 14224-style asset taxonomy and reliability data",
    "Regulatory matrix",
    "Document control",
    "SUCOFINDO technical governance",
  ],
};
