import { APP_ROUTES } from "@/lib/app-routes";

import type {
  AssessmentRouteLinks,
  RbiAssessmentRecord,
  RbiAssessmentsData,
} from "./assessment-types";

function withQuery(route: string, params: Record<string, string>) {
  return `${route}?${new URLSearchParams(params).toString()}`;
}

function assetRoute(assetId: string) {
  return `${APP_ROUTES.assets.register}/${assetId}`;
}

function linkedRoutes(assetId: string, assessmentId: string): AssessmentRouteLinks {
  return {
    assessmentDetail: `${APP_ROUTES.rbi.assessments}/${assessmentId.toLowerCase()}`,
    assetProfile: assetRoute(assetId),
    evidence: `${assetRoute(assetId)}/documents`,
    anomalies: `${assetRoute(assetId)}/anomalies-recommendations`,
    recommendations: withQuery(APP_ROUTES.anomalies.recommendations, { assetId, status: "open" }),
    assignReviewer: withQuery("/administration/approval-workflows", { assessmentId }),
    revalidation: withQuery(APP_ROUTES.rbi.revalidation, { assetId, assessmentId }),
  };
}

function assessmentRecord(record: Omit<RbiAssessmentRecord, "id" | "linkedRoutes">): RbiAssessmentRecord {
  return {
    ...record,
    id: record.assessmentId.toLowerCase(),
    linkedRoutes: linkedRoutes(record.assetId, record.assessmentId),
  };
}

// TODO(api-integration): Replace this local payload with a NestJS assessments endpoint
// joined to PostgreSQL asset master, review workflow, evidence/document metadata,
// anomalies/recommendations, and FastAPI RBI analytics outputs for PoF/CoF scoring.
export const RBI_ASSESSMENTS_DATA: RbiAssessmentsData = {
  totalPortfolioAssessments: 64,
  kpis: [
    { id: "total", label: "Total Assessments", value: 64, marker: "SPM-01 RBI campaign", tone: "blue" },
    { id: "backlog", label: "Review Backlog", value: 14, marker: "Peer/governance/client review", tone: "orange", chip: "In Review" },
    { id: "approved", label: "Approved", value: 32, marker: "Issued or ready to issue", tone: "emerald", chip: "Approved" },
    { id: "revalidation", label: "Requires Revalidation", value: 9, marker: "Renewal planning queue", tone: "violet", chip: "Requires Revalidation" },
    { id: "high-risk", label: "High-Risk Assessments", value: 11, marker: "High consequence focus", tone: "red", chip: "High Risk" },
    { id: "overdue", label: "Overdue Assessment", value: 6, marker: "Action needed this cycle", tone: "red", chip: "Overdue Assessment" },
  ],
  records: [
    assessmentRecord({
      assessmentId: "RBI-2026-001",
      assetSystem: "V-101 Inlet Separator",
      assetId: "v-101",
      status: "In Review",
      assessor: "Budi Santoso",
      reviewStage: "Peer Review",
      riskLevel: "Medium-High",
      lastModified: "2026-06-11T09:14:00.000+07:00",
      lastModifiedLabel: "11 Jun 2026 09:14",
      approvalStatus: "Pending",
      nextAction: "Provide additional corrosion data",
      assetClass: "Pressure Vessel",
      standardMapping: "API 510-style / API 580-style",
      primaryDamageMechanism: "Internal CO2 corrosion; thinning at CML/TML locations",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-002",
      assetSystem: "V-102 Test Separator",
      assetId: "v-102",
      status: "Draft",
      assessor: "Dewi Lestari",
      reviewStage: "Assessor Review",
      riskLevel: "Medium",
      lastModified: "2026-06-10T16:42:00.000+07:00",
      lastModifiedLabel: "10 Jun 2026 16:42",
      approvalStatus: "Not Submitted",
      nextAction: "Continue assessment",
      assetClass: "Pressure Vessel",
      standardMapping: "API 510-style / API 580-style",
      primaryDamageMechanism: "H2S-related susceptibility screening",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-003",
      assetSystem: "V-103 HP Separator",
      assetId: "v-103",
      status: "In Review",
      assessor: "Rizky Pratama",
      reviewStage: "Technical Governance Review",
      riskLevel: "High",
      lastModified: "2026-06-12T08:30:00.000+07:00",
      lastModifiedLabel: "12 Jun 2026 08:30",
      approvalStatus: "Awaiting Evidence",
      nextAction: "Submit NDT reports",
      assetClass: "Pressure Vessel",
      standardMapping: "API 510-style / API 581-style analytics",
      primaryDamageMechanism: "H2S susceptibility; internal CO2 corrosion",
      evidenceStatus: "Awaiting Evidence",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-004",
      assetSystem: "V-110 Gas Scrubber",
      assetId: "v-110",
      status: "Approved",
      assessor: "Budi Santoso",
      reviewStage: "Final Approval",
      riskLevel: "Low",
      lastModified: "2026-06-08T14:55:00.000+07:00",
      lastModifiedLabel: "08 Jun 2026 14:55",
      approvalStatus: "Approved",
      nextAction: "Issue report",
      assetClass: "Pressure Vessel",
      standardMapping: "API 510-style / API 580-style",
      primaryDamageMechanism: "Internal CO2 corrosion",
      evidenceStatus: "Complete",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-005",
      assetSystem: "V-115 KO Drum",
      assetId: "v-115",
      status: "Pending Approval",
      assessor: "Dewi Lestari",
      reviewStage: "Client Review",
      riskLevel: "Medium",
      lastModified: "2026-06-09T11:20:00.000+07:00",
      lastModifiedLabel: "09 Jun 2026 11:20",
      approvalStatus: "Pending",
      nextAction: "Client comments",
      assetClass: "Pressure Vessel",
      standardMapping: "API 510-style / API 580-style",
      primaryDamageMechanism: "Nozzle coating breakdown; localized pitting",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-006",
      assetSystem: "HE-201 Crude Heater",
      assetId: "he-201",
      status: "Overdue Assessment",
      assessor: "Rizky Pratama",
      reviewStage: "Assessor Review",
      riskLevel: "High",
      lastModified: "2026-06-05T10:11:00.000+07:00",
      lastModifiedLabel: "05 Jun 2026 10:11",
      approvalStatus: "Not Submitted",
      nextAction: "Update assessment",
      assetClass: "Heat Transfer Equipment",
      standardMapping: "API 580-style / API 581-style analytics",
      primaryDamageMechanism: "Corrosion under insulation; coking concern",
      evidenceStatus: "Missing Critical Evidence",
      overdue: true,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-007",
      assetSystem: "HE-202 Heat Exchanger",
      assetId: "he-202",
      status: "In Review",
      assessor: "Budi Santoso",
      reviewStage: "Peer Review",
      riskLevel: "Medium-High",
      lastModified: "2026-06-11T13:05:00.000+07:00",
      lastModifiedLabel: "11 Jun 2026 13:05",
      approvalStatus: "Rejected for Revision",
      nextAction: "Revise and resubmit",
      assetClass: "Heat Transfer Equipment",
      standardMapping: "API 580-style / API 581-style analytics",
      primaryDamageMechanism: "Gasket degradation; corrosion under insulation",
      evidenceStatus: "Rejected for Revision",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-008",
      assetSystem: "TK-301 Crude Storage Tank",
      assetId: "tk-301",
      status: "Approved",
      assessor: "Dewi Lestari",
      reviewStage: "Final Approval",
      riskLevel: "Medium",
      lastModified: "2026-06-07T15:40:00.000+07:00",
      lastModifiedLabel: "07 Jun 2026 15:40",
      approvalStatus: "Approved",
      nextAction: "Archive evidence",
      assetClass: "Storage Tank",
      standardMapping: "API 653-style / API 580-style",
      primaryDamageMechanism: "External atmospheric corrosion; localized pitting",
      evidenceStatus: "Complete",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-009",
      assetSystem: "TK-302 Produced Water Tank",
      assetId: "tk-302",
      status: "Requires Revalidation",
      assessor: "Rizky Pratama",
      reviewStage: "Assessor Review",
      riskLevel: "Medium-High",
      lastModified: "2026-06-06T09:22:00.000+07:00",
      lastModifiedLabel: "06 Jun 2026 09:22",
      approvalStatus: "Awaiting Evidence",
      nextAction: "Update corrosion data",
      assetClass: "Storage Tank",
      standardMapping: "API 653-style / API 581-style analytics",
      primaryDamageMechanism: "MIC risk; produced-water corrosion",
      evidenceStatus: "Awaiting Evidence",
      overdue: false,
      requiresRevalidation: true,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-010",
      assetSystem: "P-201A/B Crude Transfer Pumps",
      assetId: "p-201ab",
      status: "In Review",
      assessor: "Budi Santoso",
      reviewStage: "Technical Governance Review",
      riskLevel: "Medium",
      lastModified: "2026-06-11T10:33:00.000+07:00",
      lastModifiedLabel: "11 Jun 2026 10:33",
      approvalStatus: "Pending",
      nextAction: "Provide vibration data",
      assetClass: "Pump",
      standardMapping: "API 580-style / ISO 14224-style taxonomy",
      primaryDamageMechanism: "Mechanical seal leakage; vibration screening",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-011",
      assetSystem: "P-205A/B Produced Water Pumps",
      assetId: "p-205ab",
      status: "Draft",
      assessor: "Dewi Lestari",
      reviewStage: "Assessor Review",
      riskLevel: "Low",
      lastModified: "2026-06-09T16:18:00.000+07:00",
      lastModifiedLabel: "09 Jun 2026 16:18",
      approvalStatus: "Not Submitted",
      nextAction: "Continue assessment",
      assetClass: "Pump",
      standardMapping: "API 580-style / ISO 14224-style taxonomy",
      primaryDamageMechanism: "Mechanical seal leakage",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-012",
      assetSystem: "P-211 Chemical Injection Pump",
      assetId: "p-211",
      status: "Pending Approval",
      assessor: "Rizky Pratama",
      reviewStage: "Client Review",
      riskLevel: "Medium",
      lastModified: "2026-06-08T12:21:00.000+07:00",
      lastModifiedLabel: "08 Jun 2026 12:21",
      approvalStatus: "Pending",
      nextAction: "Client comments",
      assetClass: "Pump",
      standardMapping: "API 580-style / ISO 14224-style taxonomy",
      primaryDamageMechanism: "Flange leakage; gasket degradation",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-013",
      assetSystem: "C-501 Gas Compressor",
      assetId: "c-501",
      status: "In Review",
      assessor: "Budi Santoso",
      reviewStage: "Technical Governance Review",
      riskLevel: "High",
      lastModified: "2026-06-12T07:55:00.000+07:00",
      lastModifiedLabel: "12 Jun 2026 07:55",
      approvalStatus: "Awaiting Evidence",
      nextAction: "Submit PSV docs",
      assetClass: "Rotating Equipment",
      standardMapping: "API 570-style / API 580-style",
      primaryDamageMechanism: "Vibration fatigue; PSV documentation mismatch",
      evidenceStatus: "Awaiting Evidence",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-014",
      assetSystem: "C-502 Vapor Recovery Compressor",
      assetId: "c-502",
      status: "Approved",
      assessor: "Dewi Lestari",
      reviewStage: "Final Approval",
      riskLevel: "Medium",
      lastModified: "2026-06-07T13:50:00.000+07:00",
      lastModifiedLabel: "07 Jun 2026 13:50",
      approvalStatus: "Approved",
      nextAction: "Issue report",
      assetClass: "Rotating Equipment",
      standardMapping: "API 580-style / ISO 14224-style taxonomy",
      primaryDamageMechanism: "Vibration fatigue",
      evidenceStatus: "Complete",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-015",
      assetSystem: "PL-601 Crude Export Line",
      assetId: "pl-601",
      status: "Overdue Assessment",
      assessor: "Rizky Pratama",
      reviewStage: "Assessor Review",
      riskLevel: "High",
      lastModified: "2026-06-04T08:19:00.000+07:00",
      lastModifiedLabel: "04 Jun 2026 08:19",
      approvalStatus: "Not Submitted",
      nextAction: "Update assessment",
      assetClass: "Piping Circuit",
      standardMapping: "API 570-style / API 581-style analytics",
      primaryDamageMechanism: "External corrosion; coating breakdown",
      evidenceStatus: "Missing Critical Evidence",
      overdue: true,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-016",
      assetSystem: "CIR-CRUDE-02",
      assetId: "cir-crude-02",
      status: "Requires Revalidation",
      assessor: "Budi Santoso",
      reviewStage: "Assessor Review",
      riskLevel: "Medium-High",
      lastModified: "2026-06-06T11:07:00.000+07:00",
      lastModifiedLabel: "06 Jun 2026 11:07",
      approvalStatus: "Awaiting Evidence",
      nextAction: "Validate NDT reports",
      assetClass: "Piping Circuit",
      standardMapping: "API 570-style / API 580-style",
      primaryDamageMechanism: "Erosion-corrosion at high-velocity elbows",
      evidenceStatus: "Awaiting Evidence",
      overdue: false,
      requiresRevalidation: true,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-017",
      assetSystem: "CIR-GAS-01",
      assetId: "cir-gas-01",
      status: "Approved",
      assessor: "Dewi Lestari",
      reviewStage: "Final Approval",
      riskLevel: "Low",
      lastModified: "2026-06-05T14:28:00.000+07:00",
      lastModifiedLabel: "05 Jun 2026 14:28",
      approvalStatus: "Approved",
      nextAction: "Archive evidence",
      assetClass: "Piping Circuit",
      standardMapping: "API 570-style / API 580-style",
      primaryDamageMechanism: "Internal CO2 corrosion",
      evidenceStatus: "Complete",
      overdue: false,
      requiresRevalidation: false,
    }),
    assessmentRecord({
      assessmentId: "RBI-2026-018",
      assetSystem: "CIR-PW-05",
      assetId: "cir-pw-05",
      status: "In Review",
      assessor: "Rizky Pratama",
      reviewStage: "Peer Review",
      riskLevel: "Medium",
      lastModified: "2026-06-10T15:32:00.000+07:00",
      lastModifiedLabel: "10 Jun 2026 15:32",
      approvalStatus: "Pending",
      nextAction: "Provide corrosion data",
      assetClass: "Piping Circuit",
      standardMapping: "API 570-style / API 581-style analytics",
      primaryDamageMechanism: "MIC in stagnant produced-water lines",
      evidenceStatus: "Partial",
      overdue: false,
      requiresRevalidation: false,
    }),
  ],
  workflowSummary: [
    { id: "draft", label: "Draft", count: 8, tone: "slate" },
    { id: "in-review", label: "In Review", count: 21, tone: "blue" },
    { id: "technical-review", label: "Technical Review", count: 10, tone: "orange" },
    { id: "awaiting-approval", label: "Awaiting Approval", count: 9, tone: "emerald" },
    { id: "revalidation-required", label: "Revalidation Required", count: 9, tone: "violet" },
  ],
  reviewBacklog: [
    { stage: "Assessor Review", count: 18 },
    { stage: "Peer Review", count: 7 },
    { stage: "Technical Governance Review", count: 10 },
    { stage: "Client Review", count: 5 },
    { stage: "Final Approval", count: 9 },
  ],
  highRiskAttention: [
    {
      id: "attention-v-103",
      assetSystem: "V-103 HP Separator",
      issue: "H2S susceptibility, internal CO2 corrosion",
      href: withQuery(APP_ROUTES.rbi.riskAnalytics, { assetId: "v-103" }),
    },
    {
      id: "attention-c-501",
      assetSystem: "C-501 Gas Compressor",
      issue: "Vibration fatigue, PSV documentation mismatch",
      href: withQuery(APP_ROUTES.rbi.riskAnalytics, { assetId: "c-501" }),
    },
    {
      id: "attention-pl-601",
      assetSystem: "PL-601 Crude Export Line",
      issue: "External corrosion, coating breakdown",
      href: withQuery(APP_ROUTES.rbi.riskRegister, { assetId: "pl-601" }),
    },
    {
      id: "attention-tk-302",
      assetSystem: "TK-302 Produced Water Tank",
      issue: "MIC risk, produced-water corrosion",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "tk-302" }),
    },
  ],
};
