import { APP_ROUTES } from "@/lib/app-routes";

import type { IntegrityRbiOverviewData } from "./integrity-rbi-overview-types";

function withQuery(route: string, params: Record<string, string>) {
  return `${route}?${new URLSearchParams(params).toString()}`;
}

function assetRoute(assetId: string) {
  return `${APP_ROUTES.assets.register}/${assetId}`;
}

// TODO(api-integration): Replace this local payload with a NestJS Integrity/RBI
// overview endpoint and FastAPI RBI analytics rollups backed by PostgreSQL and
// TimescaleDB asset, inspection, evidence, anomaly, recommendation, audit, and
// operating data tables.
export const INTEGRITY_RBI_OVERVIEW_DATA: IntegrityRbiOverviewData = {
  facility: {
    id: "spm-01-north-block",
    name: "SPM-01 Instalasi Stasiun Pengumpul Minyak \u2014 North Block Gathering Station",
    type: "Upstream oil and gas gathering station",
    owner: "SUCOFINDO \u2014 Asset Integrity & RBI Services",
    currentUser: "Frido Satrio \u2014 SUCOFINDO \u2014 Superadmin",
    operatingMode: [
      "Continuous 24/7 brownfield operation",
      "Mid-life facility",
      "Mixed legacy documentation",
      "Ongoing RBI baseline implementation",
      "Active inspection/certification renewal campaign",
    ],
    throughput: [
      { id: "gross-liquid", label: "Gross liquid handling", value: "22,000 BOPD" },
      { id: "crude-export", label: "Crude export", value: "16,500 BOPD" },
      { id: "associated-gas", label: "Associated gas", value: "18 MMSCFD" },
      { id: "produced-water", label: "Produced-water handling", value: "14,000 BWPD" },
      { id: "onsite-storage", label: "Onsite storage", value: "6,500 bbl" },
    ],
  },
  kpis: [
    {
      id: "total-assets",
      label: "Total Assets",
      value: "142",
      marker: "SPM-01 portfolio",
      tone: "blue",
      href: APP_ROUTES.assets.register,
    },
    {
      id: "high-risk",
      label: "High-Risk Assets",
      value: "15",
      marker: "10.6% of assets",
      tone: "red",
      href: withQuery(APP_ROUTES.rbi.riskRegister, { risk: "high" }),
    },
    {
      id: "completion",
      label: "RBI Assessment Completion",
      value: "78%",
      marker: "Baseline campaign",
      tone: "emerald",
      href: APP_ROUTES.rbi.assessments,
    },
    {
      id: "overdue-inspections",
      label: "Overdue Inspections",
      value: "19",
      marker: "31 due within 90 days",
      tone: "orange",
      href: withQuery(APP_ROUTES.inspections.schedule, { status: "overdue" }),
    },
    {
      id: "next-revalidation",
      label: "Next Revalidation",
      value: "18 Jul 2026",
      marker: "V-101 Inlet Separator",
      tone: "cyan",
      href: APP_ROUTES.rbi.revalidation,
    },
    {
      id: "actions-anomalies",
      label: "Open Recommendations / Active Anomalies",
      value: "37 / 29",
      marker: "8 corrective actions overdue",
      tone: "violet",
      href: APP_ROUTES.anomalies.recommendations,
    },
  ],
  childPages: [
    {
      id: "risk-register",
      name: "Risk Register",
      descriptor: "Asset-level PoF, CoF, risk driver, and mitigation table.",
      href: APP_ROUTES.rbi.riskRegister,
      tone: "red",
    },
    {
      id: "risk-analytics",
      name: "Risk Analytics",
      descriptor: "Portfolio risk matrix, trend, scenario, and coverage analytics.",
      href: APP_ROUTES.rbi.riskAnalytics,
      tone: "blue",
    },
    {
      id: "assessments",
      name: "Assessments",
      descriptor: "RBI workstage progress and technical review packages.",
      href: APP_ROUTES.rbi.assessments,
      tone: "emerald",
    },
    {
      id: "revalidation",
      name: "Revalidation",
      descriptor: "Upcoming reassessment and renewal campaign plan.",
      href: APP_ROUTES.rbi.revalidation,
      tone: "orange",
    },
    {
      id: "iow-moc",
      name: "IOW/MOC",
      descriptor: "Integrity operating window and management-of-change triggers.",
      href: APP_ROUTES.rbi.iowMocTriggers,
      tone: "cyan",
    },
    {
      id: "ffs-rla",
      name: "FFS/RLA",
      descriptor: "Fitness-for-service and remaining-life assessment references.",
      href: APP_ROUTES.rbi.ffsRla,
      tone: "violet",
    },
    {
      id: "methodology",
      name: "Methodology",
      descriptor: "RBI method basis, standards mapping, and governance labels.",
      href: APP_ROUTES.rbi.methodologyGovernance,
      tone: "slate",
    },
  ],
  riskDistribution: [
    { level: "high", label: "High Risk", count: 15 },
    { level: "medium-high", label: "Medium-High", count: 43 },
    { level: "medium", label: "Medium", count: 56 },
    { level: "low", label: "Low", count: 28 },
  ],
  riskMatrix: [
    { probability: 5, consequence: 1, count: 0, zone: "medium" },
    { probability: 5, consequence: 2, count: 1, zone: "medium" },
    { probability: 5, consequence: 3, count: 2, zone: "medium" },
    { probability: 5, consequence: 4, count: 3, zone: "high" },
    { probability: 5, consequence: 5, count: 4, zone: "high" },
    { probability: 4, consequence: 1, count: 2, zone: "medium" },
    { probability: 4, consequence: 2, count: 3, zone: "medium" },
    { probability: 4, consequence: 3, count: 5, zone: "medium" },
    { probability: 4, consequence: 4, count: 5, zone: "high" },
    { probability: 4, consequence: 5, count: 7, zone: "high" },
    { probability: 3, consequence: 1, count: 5, zone: "low" },
    { probability: 3, consequence: 2, count: 8, zone: "medium" },
    { probability: 3, consequence: 3, count: 13, zone: "medium" },
    { probability: 3, consequence: 4, count: 10, zone: "medium" },
    { probability: 3, consequence: 5, count: 2, zone: "high" },
    { probability: 2, consequence: 1, count: 8, zone: "low" },
    { probability: 2, consequence: 2, count: 14, zone: "low" },
    { probability: 2, consequence: 3, count: 18, zone: "medium" },
    { probability: 2, consequence: 4, count: 7, zone: "medium" },
    { probability: 2, consequence: 5, count: 3, zone: "medium" },
    { probability: 1, consequence: 1, count: 8, zone: "low" },
    { probability: 1, consequence: 2, count: 6, zone: "low" },
    { probability: 1, consequence: 3, count: 5, zone: "low" },
    { probability: 1, consequence: 4, count: 2, zone: "medium" },
    { probability: 1, consequence: 5, count: 1, zone: "medium" },
  ],
  damageMechanisms: [
    { id: "internal-co2-corrosion", label: "Internal CO2 corrosion", count: 24 },
    { id: "external-atmospheric-corrosion", label: "External atmospheric corrosion", count: 18 },
    { id: "localized-pitting", label: "Localized pitting", count: 16 },
    { id: "under-deposit-corrosion", label: "Under-deposit corrosion", count: 15 },
    { id: "cui", label: "CUI", count: 12 },
    { id: "mic-produced-water", label: "MIC in produced-water lines", count: 11 },
    { id: "erosion-corrosion", label: "Erosion-corrosion", count: 10 },
    { id: "vibration-fatigue", label: "Vibration fatigue", count: 8 },
    { id: "flange-leakage", label: "Flange leakage", count: 7 },
    { id: "cml-thinning", label: "Thinning at CML/TMLs", count: 6 },
  ],
  inspectionEffectiveness: {
    score: 72,
    items: [
      { id: "current", label: "Current inspections", value: 52, tone: "emerald" },
      { id: "due-90", label: "Due within 90 days", value: 31, tone: "orange" },
      { id: "overdue", label: "Overdue", value: 19, tone: "red" },
      { id: "pending-validation", label: "Pending validation", value: 22, tone: "blue" },
      { id: "insufficient-history", label: "Insufficient history", value: 18, tone: "slate" },
    ],
  },
  assessmentCompletion: [
    { id: "pressure-vessels", label: "Pressure Vessels", percent: 84 },
    { id: "piping-circuits", label: "Piping Circuits", percent: 72 },
    { id: "storage-tanks", label: "Storage Tanks", percent: 76 },
    { id: "psv-relief", label: "PSVs / Relief Devices", percent: 81 },
    { id: "skids-packages", label: "Skids / Packages", percent: 69 },
    { id: "critical-valves", label: "Critical Valves", percent: 88 },
  ],
  revalidationSchedule: [
    {
      id: "rev-v-101",
      assetTag: "V-101",
      assetName: "Inlet Separator",
      dueDate: "18 Jul 2026",
      status: "Due Soon",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "v-101" }),
    },
    {
      id: "rev-v-103",
      assetTag: "V-103",
      assetName: "HP Separator",
      dueDate: "12 Aug 2026",
      status: "Planned",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "v-103" }),
    },
    {
      id: "rev-tk-301",
      assetTag: "TK-301",
      assetName: "Crude Storage Tank",
      dueDate: "28 Sep 2026",
      status: "Planned",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "tk-301" }),
    },
    {
      id: "rev-pl-601",
      assetTag: "PL-601",
      assetName: "Crude Export Line",
      dueDate: "15 Oct 2026",
      status: "Planned",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "pl-601" }),
    },
    {
      id: "rev-c-501",
      assetTag: "C-501",
      assetName: "Gas Compressor",
      dueDate: "05 Nov 2026",
      status: "Planned",
      href: withQuery(APP_ROUTES.rbi.revalidation, { assetId: "c-501" }),
    },
  ],
  topHighRiskAssets: [
    {
      id: "top-v-101",
      assetTag: "V-101",
      equipmentSystem: "Inlet Separator",
      riskScore: 19.2,
      rank: 1,
      drivers: ["CO2 Corrosion", "Thinning"],
      href: assetRoute("v-101"),
    },
    {
      id: "top-pl-601",
      assetTag: "PL-601",
      equipmentSystem: "Crude Export Line",
      riskScore: 16.8,
      rank: 2,
      drivers: ["External Corrosion", "Pitting"],
      href: assetRoute("pl-601"),
    },
    {
      id: "top-tk-301",
      assetTag: "TK-301",
      equipmentSystem: "Crude Storage Tank",
      riskScore: 16.1,
      rank: 3,
      drivers: ["Internal Corrosion", "CML Thinning"],
      href: assetRoute("tk-301"),
    },
    {
      id: "top-he-201",
      assetTag: "HE-201",
      equipmentSystem: "Crude Heater",
      riskScore: 15.4,
      rank: 4,
      drivers: ["HT Damage", "Coking"],
      href: assetRoute("he-201"),
    },
    {
      id: "top-c-501",
      assetTag: "C-501",
      equipmentSystem: "Gas Compressor",
      riskScore: 14.2,
      rank: 5,
      drivers: ["Vibration", "Fatigue"],
      href: assetRoute("c-501"),
    },
  ],
  integrityIssues: [
    {
      id: "issue-psv-doc",
      severity: "critical",
      title: "PSV set-pressure documentation mismatch",
      date: "09 Jun 2026",
      href: withQuery(APP_ROUTES.certification.evidencePack, { package: "psv-calibration" }),
    },
    {
      id: "issue-pl-601",
      severity: "high",
      title: "Overdue NDT report validation on PL-601",
      date: "08 Jun 2026",
      href: withQuery(APP_ROUTES.inspections.findings, { assetId: "pl-601", status: "overdue-validation" }),
    },
    {
      id: "issue-tk-301-roof",
      severity: "high",
      title: "Expired inspection certificate: TK-301 Roof",
      date: "07 Jun 2026",
      href: withQuery(APP_ROUTES.certification.register, { assetId: "tk-301", status: "expired" }),
    },
    {
      id: "issue-pid",
      severity: "medium",
      title: "Incomplete P&ID revision control, outdated revision",
      date: "06 Jun 2026",
      href: withQuery(APP_ROUTES.documents.register, { issue: "pid-revision-control" }),
    },
    {
      id: "issue-calibration",
      severity: "medium",
      title: "Missing calibration evidence: PT-403, TT-301",
      date: "05 Jun 2026",
      href: withQuery(APP_ROUTES.certification.evidencePack, { evidence: "missing-calibration" }),
    },
  ],
  recentAssessments: [
    {
      id: "assess-v-110",
      assetTag: "V-110",
      method: "API 580 Level 2",
      assessmentDate: "05 Jun 2026",
      rank: 6,
      status: "Completed",
      href: `${APP_ROUTES.rbi.assessments}/spm-01-v-110`,
    },
    {
      id: "assess-p-201ab",
      assetTag: "P-201A/B",
      method: "API 580 Level 2",
      assessmentDate: "04 Jun 2026",
      rank: 7,
      status: "In Review",
      href: `${APP_ROUTES.rbi.assessments}/spm-01-p-201ab`,
    },
    {
      id: "assess-cir-gas-01",
      assetTag: "CIR-GAS-01",
      method: "API 580 Level 1",
      assessmentDate: "03 Jun 2026",
      rank: 8,
      status: "Completed",
      href: `${APP_ROUTES.rbi.assessments}/spm-01-cir-gas-01`,
    },
    {
      id: "assess-sdv-701",
      assetTag: "SDV-701",
      method: "API 580 Level 1",
      assessmentDate: "02 Jun 2026",
      rank: 5,
      status: "In Review",
      href: `${APP_ROUTES.rbi.assessments}/spm-01-sdv-701`,
    },
    {
      id: "assess-psv-1203",
      assetTag: "PSV-1203",
      method: "API 520/580",
      assessmentDate: "31 May 2026",
      rank: 4,
      status: "Completed",
      href: `${APP_ROUTES.rbi.assessments}/spm-01-psv-1203`,
    },
  ],
  governanceStandards: [
    {
      id: "api-580-581",
      label: "API 580/581",
      category: "RBI Methodology",
      status: "In Use",
      href: APP_ROUTES.rbi.methodologyGovernance,
    },
    {
      id: "api-510",
      label: "API 510",
      category: "Pressure Vessel Inspection",
      status: "In Use",
      href: APP_ROUTES.governance.regulatoryLibrary,
    },
    {
      id: "api-570",
      label: "API 570",
      category: "Piping Inspection",
      status: "In Use",
      href: APP_ROUTES.governance.regulatoryLibrary,
    },
    {
      id: "api-653",
      label: "API 653",
      category: "Tank Inspection",
      status: "In Use",
      href: APP_ROUTES.governance.regulatoryLibrary,
    },
    {
      id: "iso-14224",
      label: "ISO 14224",
      category: "Data Taxonomy",
      status: "In Use",
      href: "/administration/asset-taxonomy",
    },
    {
      id: "moc-iow",
      label: "MOC/IOW Trigger Review",
      category: "Integrity Governance",
      status: "Active",
      href: APP_ROUTES.rbi.iowMocTriggers,
    },
    {
      id: "regulatory-matrix",
      label: "Regulatory & Compliance Matrix",
      category: "Governance Mapping",
      status: "Active",
      href: "/compliance-certification/regulatory-matrix",
    },
  ],
  workflow: {
    healthPercent: 74,
    status: "Healthy",
    stages: [
      {
        id: "assessment",
        label: "Assessment",
        href: APP_ROUTES.rbi.assessments,
        metrics: [
          { label: "In Progress", value: 18, tone: "blue" },
          { label: "Due Soon", value: 7, tone: "orange" },
          { label: "Blocked", value: 2, tone: "red" },
        ],
      },
      {
        id: "review",
        label: "Review",
        href: APP_ROUTES.rbi.assessments,
        metrics: [
          { label: "Under Review", value: 14, tone: "blue" },
          { label: "Waiting Info", value: 5, tone: "orange" },
          { label: "Overdue", value: 2, tone: "red" },
        ],
      },
      {
        id: "approval",
        label: "Approval",
        href: "/administration/approval-workflows",
        metrics: [
          { label: "Ready for Approval", value: 9, tone: "blue" },
          { label: "Approved", value: 21, tone: "emerald" },
          { label: "Rejected", value: 1, tone: "red" },
        ],
      },
      {
        id: "revalidation",
        label: "Revalidation",
        href: APP_ROUTES.rbi.revalidation,
        metrics: [
          { label: "Planned", value: 32, tone: "blue" },
          { label: "Due within 90 days", value: 12, tone: "orange" },
          { label: "Overdue", value: 6, tone: "red" },
        ],
      },
      {
        id: "mitigation",
        label: "Mitigation Planning",
        href: APP_ROUTES.anomalies.actionTracker,
        metrics: [
          { label: "Open Actions", value: 37, tone: "orange" },
          { label: "In Progress", value: 16, tone: "blue" },
          { label: "Closed", value: 21, tone: "emerald" },
        ],
      },
    ],
  },
};
