import { APP_ROUTES } from "@/lib/app-routes";

import type { RiskRegisterData, RiskRegisterRouteLinks } from "./risk-register-types";

const facilityId = "spm-01-north-block";

function withQuery(route: string, params: Record<string, string>) {
  return `${route}?${new URLSearchParams(params).toString()}`;
}

function assetRoute(assetId: string) {
  return `${APP_ROUTES.assets.register}/${assetId}`;
}

function linkedRoutes(assetId: string): RiskRegisterRouteLinks {
  return {
    assetDetail: assetRoute(assetId),
    inspectionPlanning: withQuery(APP_ROUTES.inspections.plan, { assetId }),
    anomalies: `${assetRoute(assetId)}/anomalies-recommendations`,
    documentsEvidence: `${assetRoute(assetId)}/documents`,
    riskAnalytics: withQuery(APP_ROUTES.rbi.riskAnalytics, { assetId }),
    riskMatrix: "/administration/risk-matrix",
    recommendation: withQuery(APP_ROUTES.anomalies.recommendations, { assetId, status: "open" }),
  };
}

// TODO(api-integration): Replace these typed mock records with a NestJS Risk Register
// query endpoint. The endpoint should join PostgreSQL asset master, RBI risk records,
// inspection plan/history, anomaly/recommendation, certificate/evidence, document
// metadata, and TimescaleDB operating/CML/TML time-series summaries.
export const RISK_REGISTER_DATA: RiskRegisterData = {
  totalPortfolioRecords: 142,
  facility: {
    id: facilityId,
    name: "SPM-01 Instalasi Stasiun Pengumpul Minyak \u2014 North Block Gathering Station",
    type: "Upstream oil and gas gathering station",
    owner: "SUCOFINDO \u2014 Asset Integrity & RBI Services",
    currentUser: "Frido Satrio \u2014 SUCOFINDO \u2014 Superadmin",
  },
  kpis: [
    { id: "high-risk-assets", label: "High-risk assets", value: 15, tone: "red" },
    { id: "medium-high-risk-assets", label: "Medium-high risk assets", value: 43, tone: "orange" },
    { id: "open-recommendations", label: "Open recommendations", value: 37, tone: "cyan" },
    { id: "active-anomalies", label: "Active anomalies", value: 29, tone: "violet" },
  ],
  summaryMetrics: [
    { id: "overdue-inspections", label: "Overdue inspections", value: "19", tone: "red" },
    { id: "due-90", label: "Due within 90 days", value: "31", tone: "orange" },
    { id: "inspection-plan-coverage", label: "Inspection plan coverage", value: "86%", tone: "emerald" },
    { id: "overdue-corrective-actions", label: "Overdue corrective actions", value: "8", tone: "blue" },
  ],
  frameworkLabels: [
    "API 580-style RBI",
    "API 581-style analytics",
    "API 510-style vessel inspection",
    "API 570-style piping inspection",
    "API 653-style tank inspection",
    "ISO 14224-style taxonomy",
    "Regulatory matrix",
    "Document control",
    "Audit trail",
    "MOC/IOW trigger review",
    "SUCOFINDO technical governance",
  ],
  records: [
    {
      id: "risk-v-103",
      assetId: "v-103",
      assetTag: "V-103",
      system: "Separation / Crude Stabilization",
      systemId: "separation-crude-stabilization",
      equipmentClass: "Pressure Vessel",
      assetClass: "pressure-vessel",
      pof: 4.2,
      cof: 4.3,
      riskCategory: "high",
      riskDriver: "Internal corrosion/thinning; incomplete inspection evidence",
      damageMechanism: "Internal CO2 corrosion; under-deposit corrosion",
      damageMechanismIds: ["internal-co2-corrosion", "under-deposit-corrosion"],
      inspectionEffectiveness: "low",
      nextInspectionDue: "2026-06-20",
      nextInspectionDueLabel: "20 Jun 2026",
      mitigationRecommendation: "Plan internal inspection; UT/CML review; document validation",
      priorityHighlight: true,
      recommendationStatus: "open",
      activeAnomalyCount: 2,
      openRecommendationCount: 4,
      linkedRoutes: linkedRoutes("v-103"),
    },
    {
      id: "risk-line-6-oil-101",
      assetId: "line-6-oil-101",
      assetTag: "LINE-6-OIL-101",
      system: "Crude Export",
      systemId: "crude-export",
      equipmentClass: "Piping Circuit / Flowline",
      assetClass: "piping-flowline",
      pof: 4.1,
      cof: 4.0,
      riskCategory: "high",
      riskDriver: "Internal corrosion / erosion-corrosion; missing validation",
      damageMechanism: "Erosion-corrosion at high-velocity elbows",
      damageMechanismIds: ["erosion-corrosion"],
      inspectionEffectiveness: "low",
      nextInspectionDue: "2026-07-15",
      nextInspectionDueLabel: "15 Jul 2026",
      mitigationRecommendation: "Circuit review; UT at CMLs; flow/velocity check; RBI reassessment",
      priorityHighlight: true,
      recommendationStatus: "open",
      activeAnomalyCount: 2,
      openRecommendationCount: 3,
      linkedRoutes: linkedRoutes("line-6-oil-101"),
    },
    {
      id: "risk-tk-301",
      assetId: "tk-301",
      assetTag: "TK-301",
      system: "Storage",
      systemId: "storage",
      equipmentClass: "Tank",
      assetClass: "tank",
      pof: 3.9,
      cof: 4.0,
      riskCategory: "high",
      riskDriver: "External corrosion / floor integrity; incomplete evidence",
      damageMechanism: "External atmospheric corrosion; localized pitting",
      damageMechanismIds: ["external-atmospheric-corrosion", "localized-pitting"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-07-10",
      nextInspectionDueLabel: "10 Jul 2026",
      mitigationRecommendation: "External inspection evidence completion; thickness mapping; floor UT",
      priorityHighlight: true,
      recommendationStatus: "open",
      activeAnomalyCount: 1,
      openRecommendationCount: 3,
      linkedRoutes: linkedRoutes("tk-301"),
    },
    {
      id: "risk-c-501",
      assetId: "c-501",
      assetTag: "C-501",
      system: "Gas Compression",
      systemId: "gas-compression",
      equipmentClass: "Compressor / Rotating Equipment",
      assetClass: "compressor-rotating",
      pof: 4.0,
      cof: 3.7,
      riskCategory: "high",
      riskDriver: "Vibration; discharge piping fatigue; overdue validation",
      damageMechanism: "Vibration fatigue on compressor discharge piping",
      damageMechanismIds: ["vibration-fatigue"],
      inspectionEffectiveness: "low",
      nextInspectionDue: "2026-07-05",
      nextInspectionDueLabel: "05 Jul 2026",
      mitigationRecommendation: "Vibration assessment; piping support review; anomaly close-out",
      priorityHighlight: true,
      recommendationStatus: "open",
      activeAnomalyCount: 3,
      openRecommendationCount: 3,
      linkedRoutes: linkedRoutes("c-501"),
    },
    {
      id: "risk-psv-1203",
      assetId: "psv-1203",
      assetTag: "PSV-1203",
      system: "Relief & Protection",
      systemId: "relief-protection",
      equipmentClass: "Pressure Safety Device",
      assetClass: "pressure-safety-device",
      pof: 3.8,
      cof: 3.8,
      riskCategory: "high",
      riskDriver: "Set-pressure documentation mismatch; missing calibration evidence",
      damageMechanism: "Documentation/calibration control issue",
      damageMechanismIds: ["documentation-calibration-control"],
      inspectionEffectiveness: "low",
      nextInspectionDue: "2026-06-18",
      nextInspectionDueLabel: "18 Jun 2026",
      mitigationRecommendation: "Calibration package completion; verification & documentation",
      priorityHighlight: true,
      recommendationStatus: "open",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("psv-1203"),
    },
    {
      id: "risk-v-101",
      assetId: "v-101",
      assetTag: "V-101",
      system: "Separation / Crude Stabilization",
      systemId: "separation-crude-stabilization",
      equipmentClass: "Pressure Vessel",
      assetClass: "pressure-vessel",
      pof: 3.7,
      cof: 3.9,
      riskCategory: "high",
      riskDriver: "Expired inspection certificate; CML evidence gap",
      damageMechanism: "Localized pitting; internal CO2 corrosion",
      damageMechanismIds: ["localized-pitting", "internal-co2-corrosion"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-06-26",
      nextInspectionDueLabel: "26 Jun 2026",
      mitigationRecommendation: "Renew inspection certificate; reconcile CML history; client evidence request",
      priorityHighlight: false,
      recommendationStatus: "open",
      activeAnomalyCount: 2,
      openRecommendationCount: 3,
      linkedRoutes: linkedRoutes("v-101"),
    },
    {
      id: "risk-v-110",
      assetId: "v-110",
      assetTag: "V-110",
      system: "Associated Gas",
      systemId: "associated-gas",
      equipmentClass: "Pressure Vessel",
      assetClass: "pressure-vessel",
      pof: 3.4,
      cof: 3.6,
      riskCategory: "medium-high",
      riskDriver: "Wet gas carryover; incomplete corrosion screening",
      damageMechanism: "Internal CO2 corrosion",
      damageMechanismIds: ["internal-co2-corrosion"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-08-18",
      nextInspectionDueLabel: "18 Aug 2026",
      mitigationRecommendation: "Gas scrubber inspection; update corrosion screening; verify operating envelope",
      priorityHighlight: false,
      recommendationStatus: "in-progress",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("v-110"),
    },
    {
      id: "risk-he-201",
      assetId: "he-201",
      assetTag: "HE-201",
      system: "Separation / Crude Stabilization",
      systemId: "separation-crude-stabilization",
      equipmentClass: "Heat Exchanger",
      assetClass: "heat-exchanger",
      pof: 2.9,
      cof: 3.2,
      riskCategory: "medium",
      riskDriver: "CUI screening pending at insulation transitions",
      damageMechanism: "Insulation degradation",
      damageMechanismIds: ["insulation-degradation"],
      inspectionEffectiveness: "medium-high",
      nextInspectionDue: "2026-09-02",
      nextInspectionDueLabel: "02 Sep 2026",
      mitigationRecommendation: "CUI spot check; coating repair list; update inspection workpack",
      priorityHighlight: false,
      recommendationStatus: "monitoring",
      activeAnomalyCount: 0,
      openRecommendationCount: 1,
      linkedRoutes: linkedRoutes("he-201"),
    },
    {
      id: "risk-p-201a",
      assetId: "p-201a",
      assetTag: "P-201A",
      system: "Crude Transfer",
      systemId: "crude-transfer",
      equipmentClass: "Pump",
      assetClass: "pump",
      pof: 2.7,
      cof: 3.1,
      riskCategory: "medium",
      riskDriver: "Mechanical seal leakage history; PM close-out delay",
      damageMechanism: "Mechanical seal leakage",
      damageMechanismIds: ["mechanical-seal-leakage"],
      inspectionEffectiveness: "medium-high",
      nextInspectionDue: "2026-09-18",
      nextInspectionDueLabel: "18 Sep 2026",
      mitigationRecommendation: "Seal flush check; verify spare seal; close preventive maintenance action",
      priorityHighlight: false,
      recommendationStatus: "in-progress",
      activeAnomalyCount: 1,
      openRecommendationCount: 1,
      linkedRoutes: linkedRoutes("p-201a"),
    },
    {
      id: "risk-p-205a",
      assetId: "p-205a",
      assetTag: "P-205A",
      system: "Produced Water",
      systemId: "produced-water",
      equipmentClass: "Pump",
      assetClass: "pump",
      pof: 2.4,
      cof: 2.8,
      riskCategory: "low",
      riskDriver: "Routine produced-water pump degradation under monitoring",
      damageMechanism: "Mechanical seal leakage",
      damageMechanismIds: ["mechanical-seal-leakage"],
      inspectionEffectiveness: "high",
      nextInspectionDue: "2026-11-08",
      nextInspectionDueLabel: "08 Nov 2026",
      mitigationRecommendation: "Continue vibration and seal leak checks under PM route",
      priorityHighlight: false,
      recommendationStatus: "monitoring",
      activeAnomalyCount: 0,
      openRecommendationCount: 0,
      linkedRoutes: linkedRoutes("p-205a"),
    },
    {
      id: "risk-c-502",
      assetId: "c-502",
      assetTag: "C-502",
      system: "Gas Compression",
      systemId: "gas-compression",
      equipmentClass: "Compressor / Rotating Equipment",
      assetClass: "compressor-rotating",
      pof: 3.5,
      cof: 3.4,
      riskCategory: "medium-high",
      riskDriver: "Vapor recovery compressor surge events; vibration review open",
      damageMechanism: "Vibration fatigue",
      damageMechanismIds: ["vibration-fatigue"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-08-05",
      nextInspectionDueLabel: "05 Aug 2026",
      mitigationRecommendation: "Confirm anti-surge settings; trend vibration; inspect discharge supports",
      priorityHighlight: false,
      recommendationStatus: "open",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("c-502"),
    },
    {
      id: "risk-mtr-801",
      assetId: "mtr-801",
      assetTag: "MTR-801",
      system: "Crude Export",
      systemId: "crude-export",
      equipmentClass: "Metering Skid",
      assetClass: "metering-skid",
      pof: 2.1,
      cof: 3.0,
      riskCategory: "low",
      riskDriver: "Custody metering proving interval approaching",
      damageMechanism: "Documentation/calibration control issue",
      damageMechanismIds: ["documentation-calibration-control"],
      inspectionEffectiveness: "high",
      nextInspectionDue: "2026-12-12",
      nextInspectionDueLabel: "12 Dec 2026",
      mitigationRecommendation: "Maintain proving schedule; retain calibration evidence in document control",
      priorityHighlight: false,
      recommendationStatus: "monitoring",
      activeAnomalyCount: 0,
      openRecommendationCount: 1,
      linkedRoutes: linkedRoutes("mtr-801"),
    },
    {
      id: "risk-cir-gas-01",
      assetId: "cir-gas-01",
      assetTag: "CIR-GAS-01",
      system: "Associated Gas",
      systemId: "associated-gas",
      equipmentClass: "Piping Circuit / Flowline",
      assetClass: "piping-flowline",
      pof: 3.1,
      cof: 3.5,
      riskCategory: "medium-high",
      riskDriver: "Wet gas corrosion screening requires operating data confirmation",
      damageMechanism: "Internal CO2 corrosion",
      damageMechanismIds: ["internal-co2-corrosion"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-08-28",
      nextInspectionDueLabel: "28 Aug 2026",
      mitigationRecommendation: "Confirm water dew point; update corrosion loop; add UT points at low legs",
      priorityHighlight: false,
      recommendationStatus: "in-progress",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("cir-gas-01"),
    },
    {
      id: "risk-cir-pw-05",
      assetId: "cir-pw-05",
      assetTag: "CIR-PW-05",
      system: "Produced Water",
      systemId: "produced-water",
      equipmentClass: "Piping Circuit / Flowline",
      assetClass: "piping-flowline",
      pof: 3.6,
      cof: 3.3,
      riskCategory: "medium-high",
      riskDriver: "Stagnant produced-water service; MIC screening overdue",
      damageMechanism: "MIC",
      damageMechanismIds: ["mic"],
      inspectionEffectiveness: "low",
      nextInspectionDue: "2026-07-22",
      nextInspectionDueLabel: "22 Jul 2026",
      mitigationRecommendation: "MIC screening; NDT validation; review dead-leg management",
      priorityHighlight: false,
      recommendationStatus: "open",
      activeAnomalyCount: 2,
      openRecommendationCount: 3,
      linkedRoutes: linkedRoutes("cir-pw-05"),
    },
    {
      id: "risk-sdv-701",
      assetId: "sdv-701",
      assetTag: "SDV-701",
      system: "ESD / Isolation",
      systemId: "esd-isolation",
      equipmentClass: "Shutdown Valve",
      assetClass: "shutdown-valve",
      pof: 2.8,
      cof: 3.2,
      riskCategory: "medium",
      riskDriver: "Missing calibration evidence; partial proof-test package",
      damageMechanism: "Documentation/calibration control issue",
      damageMechanismIds: ["documentation-calibration-control"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-06-30",
      nextInspectionDueLabel: "30 Jun 2026",
      mitigationRecommendation: "Complete calibration evidence; verify proof-test records; update audit trail",
      priorityHighlight: false,
      recommendationStatus: "open",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("sdv-701"),
    },
    {
      id: "risk-tk-302",
      assetId: "tk-302",
      assetTag: "TK-302",
      system: "Produced Water",
      systemId: "produced-water",
      equipmentClass: "Tank",
      assetClass: "tank",
      pof: 3.3,
      cof: 3.4,
      riskCategory: "medium-high",
      riskDriver: "Produced-water tank external evidence incomplete",
      damageMechanism: "Under-deposit corrosion; localized pitting",
      damageMechanismIds: ["under-deposit-corrosion", "localized-pitting"],
      inspectionEffectiveness: "medium",
      nextInspectionDue: "2026-08-12",
      nextInspectionDueLabel: "12 Aug 2026",
      mitigationRecommendation: "Complete external evidence; floor scan plan; produced-water chemistry review",
      priorityHighlight: false,
      recommendationStatus: "open",
      activeAnomalyCount: 1,
      openRecommendationCount: 2,
      linkedRoutes: linkedRoutes("tk-302"),
    },
    {
      id: "risk-psv-1204",
      assetId: "psv-1204",
      assetTag: "PSV-1204",
      system: "Relief & Protection",
      systemId: "relief-protection",
      equipmentClass: "Pressure Safety Device",
      assetClass: "pressure-safety-device",
      pof: 2.9,
      cof: 3.6,
      riskCategory: "medium",
      riskDriver: "Set pressure package due for renewal evidence",
      damageMechanism: "Documentation/calibration control issue",
      damageMechanismIds: ["documentation-calibration-control"],
      inspectionEffectiveness: "medium-high",
      nextInspectionDue: "2026-07-25",
      nextInspectionDueLabel: "25 Jul 2026",
      mitigationRecommendation: "Update set-pressure documentation; verify calibration certificate traceability",
      priorityHighlight: false,
      recommendationStatus: "in-progress",
      activeAnomalyCount: 0,
      openRecommendationCount: 1,
      linkedRoutes: linkedRoutes("psv-1204"),
    },
    {
      id: "risk-cir-crude-02",
      assetId: "cir-crude-02",
      assetTag: "CIR-CRUDE-02",
      system: "Crude Transfer",
      systemId: "crude-transfer",
      equipmentClass: "Piping Circuit / Flowline",
      assetClass: "piping-flowline",
      pof: 2.8,
      cof: 3.1,
      riskCategory: "medium",
      riskDriver: "CML review pending at elbow groups",
      damageMechanism: "Erosion-corrosion",
      damageMechanismIds: ["erosion-corrosion"],
      inspectionEffectiveness: "medium-high",
      nextInspectionDue: "2026-10-14",
      nextInspectionDueLabel: "14 Oct 2026",
      mitigationRecommendation: "Review CML grouping; add elbow UT checks; confirm pump discharge velocity",
      priorityHighlight: false,
      recommendationStatus: "monitoring",
      activeAnomalyCount: 0,
      openRecommendationCount: 1,
      linkedRoutes: linkedRoutes("cir-crude-02"),
    },
    {
      id: "risk-esdv-702",
      assetId: "esdv-702",
      assetTag: "ESDV-702",
      system: "ESD / Isolation",
      systemId: "esd-isolation",
      equipmentClass: "Shutdown Valve",
      assetClass: "shutdown-valve",
      pof: 2.5,
      cof: 3.0,
      riskCategory: "low",
      riskDriver: "Proof-test history current; minor documentation refresh required",
      damageMechanism: "Documentation/calibration control issue",
      damageMechanismIds: ["documentation-calibration-control"],
      inspectionEffectiveness: "high",
      nextInspectionDue: "2026-12-02",
      nextInspectionDueLabel: "02 Dec 2026",
      mitigationRecommendation: "Maintain proof-test interval; refresh calibration evidence package",
      priorityHighlight: false,
      recommendationStatus: "monitoring",
      activeAnomalyCount: 0,
      openRecommendationCount: 0,
      linkedRoutes: linkedRoutes("esdv-702"),
    },
  ],
};
