import { APP_ROUTES } from "@/lib/app-routes";

import type { RiskAnalyticsData } from "./risk-analytics-types";

const projectId = "spm-01-north-block";

function withQuery(route: string, params: Record<string, string>) {
  const query = new URLSearchParams(params);

  return `${route}?${query.toString()}`;
}

function assetRoute(assetId: string) {
  return `${APP_ROUTES.assets.register}/${assetId}`;
}

function assetLinkedRoutes(assetId: string) {
  return {
    assetDetail: assetRoute(assetId),
    inspectionHistory: `${assetRoute(assetId)}/inspection-history`,
    rbiAssessment: `${APP_ROUTES.rbi.assessments}/${projectId}-${assetId}`,
    documentEvidence: `${assetRoute(assetId)}/documents`,
    anomalies: `${assetRoute(assetId)}/anomalies-recommendations`,
    recommendations: withQuery(APP_ROUTES.anomalies.recommendations, { assetId }),
  };
}

// TODO(api-integration): Replace this module with a NestJS portfolio risk endpoint
// and FastAPI RBI calculation/scenario endpoint backed by PostgreSQL/TimescaleDB
// asset risk, inspection history, CML/TML, evidence, and trend time-series tables.
export const RISK_ANALYTICS_DATA: RiskAnalyticsData = {
  facility: {
    id: projectId,
    name: "SPM-01 Instalasi Stasiun Pengumpul Minyak \u2014 North Block Gathering Station",
    type: "Upstream oil and gas gathering station",
    owner: "SUCOFINDO \u2014 Asset Integrity & RBI Services",
    currentUser: "Frido Satrio \u2014 SUCOFINDO \u2014 Superadmin",
    operatingMode: "Continuous 24/7 brownfield operation",
    condition: [
      "Mid-life facility",
      "Mixed legacy documentation",
      "Ongoing RBI baseline implementation",
      "Active inspection/certification renewal campaign",
    ],
    throughput: {
      grossLiquidBopd: 22000,
      crudeExportBopd: 16500,
      associatedGasMmscfd: 18,
      producedWaterBwpd: 14000,
      onsiteStorageBbl: 6500,
    },
  },
  assetPopulation: [
    { id: "pressure-vessel", label: "Pressure Vessels", count: 11 },
    { id: "heat-exchanger", label: "Heaters / Heat Exchangers", count: 7 },
    { id: "storage-tank", label: "Tanks / Storage Vessels", count: 13 },
    { id: "rotating-equipment", label: "Pumps", count: 22 },
    { id: "rotating-equipment", label: "Compressors / Blowers", count: 5 },
    { id: "piping-circuit", label: "Piping Circuits / Flowlines", count: 31 },
    { id: "pressure-safety-device", label: "Pressure Safety Devices", count: 17 },
    { id: "instrumented-safety", label: "Metering / Pigging / Custody Skids", count: 8 },
    { id: "instrumented-safety", label: "ESD / SDV Assemblies", count: 10 },
    { id: "instrumented-safety", label: "Instrumented / Utility / Safety-Critical", count: 18 },
  ],
  portfolioRiskSummary: [
    { id: "high", label: "High", count: 15 },
    { id: "medium-high", label: "Medium-High", count: 43 },
    { id: "medium", label: "Medium", count: 56 },
    { id: "low", label: "Low", count: 28 },
  ],
  kpis: [
    {
      id: "total-assets",
      label: "Total Assets",
      value: 142,
      delta: "Portfolio baseline",
      href: APP_ROUTES.assets.register,
      tone: "blue",
    },
    {
      id: "high-risk-assets",
      label: "High-Risk Assets",
      value: 15,
      delta: "-3 vs last review",
      href: withQuery(APP_ROUTES.rbi.riskRegister, { risk: "high" }),
      tone: "red",
    },
    {
      id: "overdue-inspections",
      label: "Overdue Inspections",
      value: 19,
      delta: "+2 vs last review",
      href: withQuery(APP_ROUTES.inspections.schedule, { status: "overdue" }),
      tone: "orange",
    },
    {
      id: "open-recommendations",
      label: "Open Recommendations",
      value: 37,
      delta: "-5 vs last review",
      href: withQuery(APP_ROUTES.anomalies.recommendations, { status: "open" }),
      tone: "cyan",
    },
    {
      id: "active-anomalies",
      label: "Active Anomalies",
      value: 29,
      delta: "+4 vs last review",
      href: withQuery(APP_ROUTES.anomalies.register, { status: "active" }),
      tone: "violet",
    },
    {
      id: "due-within-90",
      label: "Due Within 90 Days",
      value: 31,
      delta: "-6 vs last review",
      href: withQuery(APP_ROUTES.inspections.schedule, { due: "90-days" }),
      tone: "emerald",
    },
  ],
  riskAssets: [
    {
      id: "risk-psv-1203",
      assetId: "psv-1203",
      tag: "PSV-1203",
      name: "Pressure Safety Valve 1203",
      assetType: "Pressure Safety Device",
      assetClass: "pressure-safety-device",
      probabilityBaseline: 4,
      consequenceBaseline: 5,
      probabilityMitigated: 3,
      consequenceMitigated: 5,
      riskScoreBaseline: 24.7,
      riskScoreMitigated: 18.9,
      dominantDamageMechanism: "psv-documentation-mismatch",
      dominantDamageMechanismLabel: "PSV set-pressure documentation mismatch",
      inspectionStatus: "Overdue validation",
      certificationStatus: "Immediate renewal evidence required",
      evidenceStatus: "Calibration package incomplete",
      inspectionCoveragePercent: 52,
      standards: ["API 580-style RBI", "Inspection Certification Evidence", "Document Control"],
      linkedRoutes: assetLinkedRoutes("psv-1203"),
    },
    {
      id: "risk-v-103",
      assetId: "v-103",
      tag: "V-103 HP Separator",
      name: "HP Separator",
      assetType: "Pressure Vessel",
      assetClass: "pressure-vessel",
      probabilityBaseline: 4,
      consequenceBaseline: 5,
      probabilityMitigated: 3,
      consequenceMitigated: 4,
      riskScoreBaseline: 21.9,
      riskScoreMitigated: 15.8,
      dominantDamageMechanism: "internal-co2-corrosion",
      dominantDamageMechanismLabel: "Internal CO2 corrosion",
      inspectionStatus: "Due within 90 days",
      certificationStatus: "Certificate evidence update required",
      evidenceStatus: "Partial inspection package",
      inspectionCoveragePercent: 68,
      standards: ["API 510-style vessels", "API 581-style analytics", "MOC/IOW Trigger Review"],
      linkedRoutes: assetLinkedRoutes("v-103"),
    },
    {
      id: "risk-tk-301",
      assetId: "tk-301",
      tag: "TK-301 Crude Storage Tank",
      name: "Crude Storage Tank",
      assetType: "Storage Tank",
      assetClass: "storage-tank",
      probabilityBaseline: 3,
      consequenceBaseline: 5,
      probabilityMitigated: 3,
      consequenceMitigated: 4,
      riskScoreBaseline: 19.6,
      riskScoreMitigated: 14.2,
      dominantDamageMechanism: "external-atmospheric-corrosion",
      dominantDamageMechanismLabel: "External atmospheric corrosion",
      inspectionStatus: "External inspection evidence incomplete",
      certificationStatus: "Due within 180 days",
      evidenceStatus: "Tank shell UT evidence pending",
      inspectionCoveragePercent: 61,
      standards: ["API 653-style tanks", "Document Control", "Regulatory Matrix"],
      linkedRoutes: assetLinkedRoutes("tk-301"),
    },
    {
      id: "risk-c-501",
      assetId: "c-501",
      tag: "C-501 Gas Compressor",
      name: "Gas Compressor discharge line",
      assetType: "Rotating Equipment",
      assetClass: "rotating-equipment",
      probabilityBaseline: 4,
      consequenceBaseline: 4,
      probabilityMitigated: 3,
      consequenceMitigated: 4,
      riskScoreBaseline: 18.3,
      riskScoreMitigated: 13.1,
      dominantDamageMechanism: "vibration-fatigue",
      dominantDamageMechanismLabel: "Vibration fatigue on compressor discharge piping",
      inspectionStatus: "Corrective action overdue",
      certificationStatus: "No certificate blocker",
      evidenceStatus: "Vibration trend review required",
      inspectionCoveragePercent: 58,
      standards: ["API 570-style piping", "MOC/IOW Trigger Review", "Audit Trail"],
      linkedRoutes: assetLinkedRoutes("c-501"),
    },
    {
      id: "risk-line-6-oil-101",
      assetId: "line-6-oil-101",
      tag: "LINE-6-OIL-101",
      name: "Crude Export Line",
      assetType: "Piping Circuit",
      assetClass: "piping-circuit",
      probabilityBaseline: 4,
      consequenceBaseline: 4,
      probabilityMitigated: 3,
      consequenceMitigated: 3,
      riskScoreBaseline: 16.8,
      riskScoreMitigated: 10.7,
      dominantDamageMechanism: "erosion-corrosion",
      dominantDamageMechanismLabel: "Erosion-corrosion at high-velocity elbows",
      inspectionStatus: "NDT report validation overdue",
      certificationStatus: "Not certificate driven",
      evidenceStatus: "CML/TML record needs validation",
      inspectionCoveragePercent: 63,
      standards: ["API 570-style piping", "ISO 14224-style taxonomy", "Document Control"],
      linkedRoutes: assetLinkedRoutes("line-6-oil-101"),
    },
    {
      id: "risk-v-101",
      assetId: "v-101",
      tag: "V-101 Inlet Separator",
      name: "Inlet Separator",
      assetType: "Pressure Vessel",
      assetClass: "pressure-vessel",
      probabilityBaseline: 3,
      consequenceBaseline: 5,
      probabilityMitigated: 2,
      consequenceMitigated: 4,
      riskScoreBaseline: 16.2,
      riskScoreMitigated: 9.4,
      dominantDamageMechanism: "localized-pitting",
      dominantDamageMechanismLabel: "Localized pitting",
      inspectionStatus: "Expired inspection certificate",
      certificationStatus: "Expired",
      evidenceStatus: "Urgent certificate evidence",
      inspectionCoveragePercent: 72,
      standards: ["API 510-style vessels", "Inspection Certification Evidence", "SUCOFINDO Technical Governance"],
      linkedRoutes: assetLinkedRoutes("v-101"),
    },
    {
      id: "risk-cir-pw-05",
      assetId: "cir-pw-05",
      tag: "CIR-PW-05",
      name: "Produced-water stagnant circuit",
      assetType: "Piping Circuit",
      assetClass: "piping-circuit",
      probabilityBaseline: 4,
      consequenceBaseline: 3,
      probabilityMitigated: 3,
      consequenceMitigated: 3,
      riskScoreBaseline: 15.1,
      riskScoreMitigated: 10.2,
      dominantDamageMechanism: "mic-produced-water",
      dominantDamageMechanismLabel: "MIC in stagnant produced-water lines",
      inspectionStatus: "MIC screening and NDT validation overdue",
      certificationStatus: "Not certificate driven",
      evidenceStatus: "Produced-water validation package incomplete",
      inspectionCoveragePercent: 46,
      standards: ["API 570-style piping", "API 581-style analytics", "MOC/IOW Trigger Review"],
      linkedRoutes: assetLinkedRoutes("cir-pw-05"),
    },
    {
      id: "risk-p-201a",
      assetId: "p-201a",
      tag: "P-201A",
      name: "Crude Transfer Pump A",
      assetType: "Rotating Equipment",
      assetClass: "rotating-equipment",
      probabilityBaseline: 3,
      consequenceBaseline: 3,
      probabilityMitigated: 2,
      consequenceMitigated: 3,
      riskScoreBaseline: 11.5,
      riskScoreMitigated: 7.2,
      dominantDamageMechanism: "flange-leakage",
      dominantDamageMechanismLabel: "Flange leakage",
      inspectionStatus: "Current",
      certificationStatus: "No certificate blocker",
      evidenceStatus: "Minimum documentation complete",
      inspectionCoveragePercent: 80,
      standards: ["ISO 14224-style taxonomy", "Audit Trail"],
      linkedRoutes: assetLinkedRoutes("p-201a"),
    },
    {
      id: "risk-tk-302",
      assetId: "tk-302",
      tag: "TK-302 Produced Water Tank",
      name: "Produced Water Tank",
      assetType: "Storage Tank",
      assetClass: "storage-tank",
      probabilityBaseline: 3,
      consequenceBaseline: 4,
      probabilityMitigated: 2,
      consequenceMitigated: 4,
      riskScoreBaseline: 14.8,
      riskScoreMitigated: 9.8,
      dominantDamageMechanism: "under-deposit-corrosion",
      dominantDamageMechanismLabel: "Under-deposit corrosion",
      inspectionStatus: "Waiting validation",
      certificationStatus: "Due within 180 days",
      evidenceStatus: "External inspection evidence incomplete",
      inspectionCoveragePercent: 55,
      standards: ["API 653-style tanks", "Document Control"],
      linkedRoutes: assetLinkedRoutes("tk-302"),
    },
    {
      id: "risk-he-201",
      assetId: "he-201",
      tag: "HE-201 Crude Heater",
      name: "Crude Heater",
      assetType: "Heat Exchanger",
      assetClass: "heat-exchanger",
      probabilityBaseline: 3,
      consequenceBaseline: 3,
      probabilityMitigated: 2,
      consequenceMitigated: 3,
      riskScoreBaseline: 10.9,
      riskScoreMitigated: 7.4,
      dominantDamageMechanism: "corrosion-under-insulation",
      dominantDamageMechanismLabel: "Corrosion under insulation",
      inspectionStatus: "Current",
      certificationStatus: "Evidence current",
      evidenceStatus: "CUI screening active",
      inspectionCoveragePercent: 76,
      standards: ["API 581-style analytics", "Document Control"],
      linkedRoutes: assetLinkedRoutes("he-201"),
    },
  ],
  pofDistribution: [
    { id: "pof-1", label: "1 Rare", baseline: 28, mitigated: 36 },
    { id: "pof-2", label: "2 Unlikely", baseline: 37, mitigated: 44 },
    { id: "pof-3", label: "3 Possible", baseline: 45, mitigated: 39 },
    { id: "pof-4", label: "4 Likely", baseline: 24, mitigated: 18 },
    { id: "pof-5", label: "5 Almost Certain", baseline: 8, mitigated: 5 },
  ],
  cofDistribution: [
    { id: "cof-1", label: "1 Negligible", baseline: 18, mitigated: 20 },
    { id: "cof-2", label: "2 Minor", baseline: 31, mitigated: 35 },
    { id: "cof-3", label: "3 Moderate", baseline: 44, mitigated: 43 },
    { id: "cof-4", label: "4 Major", baseline: 34, mitigated: 31 },
    { id: "cof-5", label: "5 Catastrophic", baseline: 15, mitigated: 13 },
  ],
  damageMechanismPareto: [
    { id: "internal-co2-corrosion", label: "Internal CO2 corrosion", count: 24 },
    { id: "mic-produced-water", label: "MIC in stagnant produced-water lines", count: 17 },
    { id: "localized-pitting", label: "Localized pitting", count: 14 },
    { id: "erosion-corrosion", label: "Erosion-corrosion at high-velocity elbows", count: 12 },
    { id: "external-atmospheric-corrosion", label: "External atmospheric corrosion", count: 10 },
    { id: "vibration-fatigue", label: "Vibration fatigue", count: 8 },
    { id: "psv-documentation-mismatch", label: "PSV set-pressure documentation mismatch", count: 6 },
  ],
  riskTrend: [
    { month: "Jan", baseline: 75, mitigated: 65 },
    { month: "Feb", baseline: 78, mitigated: 63 },
    { month: "Mar", baseline: 82, mitigated: 61 },
    { month: "Apr", baseline: 84, mitigated: 59 },
    { month: "May", baseline: 81, mitigated: 56 },
    { month: "Jun", baseline: 79, mitigated: 54 },
  ],
  inspectionCoverage: [
    { id: "cov-psv-1203", assetId: "psv-1203", tag: "PSV-1203", assetClass: "pressure-safety-device", coveragePercent: 52, riskScoreBaseline: 24.7, riskScoreMitigated: 18.9, radius: 9 },
    { id: "cov-v-103", assetId: "v-103", tag: "V-103", assetClass: "pressure-vessel", coveragePercent: 68, riskScoreBaseline: 21.9, riskScoreMitigated: 15.8, radius: 8 },
    { id: "cov-tk-301", assetId: "tk-301", tag: "TK-301", assetClass: "storage-tank", coveragePercent: 61, riskScoreBaseline: 19.6, riskScoreMitigated: 14.2, radius: 7 },
    { id: "cov-c-501", assetId: "c-501", tag: "C-501", assetClass: "rotating-equipment", coveragePercent: 58, riskScoreBaseline: 18.3, riskScoreMitigated: 13.1, radius: 8 },
    { id: "cov-line-6-oil-101", assetId: "line-6-oil-101", tag: "LINE-6-OIL-101", assetClass: "piping-circuit", coveragePercent: 63, riskScoreBaseline: 16.8, riskScoreMitigated: 10.7, radius: 7 },
    { id: "cov-cir-pw-05", assetId: "cir-pw-05", tag: "CIR-PW-05", assetClass: "piping-circuit", coveragePercent: 46, riskScoreBaseline: 15.1, riskScoreMitigated: 10.2, radius: 6 },
    { id: "cov-v-101", assetId: "v-101", tag: "V-101", assetClass: "pressure-vessel", coveragePercent: 72, riskScoreBaseline: 16.2, riskScoreMitigated: 9.4, radius: 6 },
  ],
  mitigationScenarios: [
    {
      id: "baseline",
      label: "Current Baseline",
      highRiskCount: 15,
      averageRiskReductionPercent: 0,
      actionCoveragePercent: 42,
      readinessScore: 74,
      note: "Current reviewed risk basis for active campaign.",
    },
    {
      id: "planned-90",
      label: "Planned 90-Day Actions",
      highRiskCount: 13,
      averageRiskReductionPercent: 11,
      actionCoveragePercent: 61,
      readinessScore: 78,
      note: "Overdue NDT validation and corrective action close-out.",
    },
    {
      id: "cert-renewal",
      label: "Certificate Renewal Push",
      highRiskCount: 12,
      averageRiskReductionPercent: 14,
      actionCoveragePercent: 68,
      readinessScore: 80,
      note: "PSV and vessel evidence updates prioritized.",
    },
    {
      id: "full-mitigation",
      label: "Full Mitigation",
      highRiskCount: 11,
      averageRiskReductionPercent: 22,
      actionCoveragePercent: 84,
      readinessScore: 86,
      note: "Inspection, documentation, and recommendation closure aligned.",
    },
  ],
  riskInsights: [
    {
      id: "concentration",
      text: "15 high-risk assets concentrated in separators, piping circuits, and pressure safety devices.",
      href: withQuery(APP_ROUTES.rbi.riskRegister, { risk: "high" }),
      tone: "red",
    },
    {
      id: "co2",
      text: "Highest recurring mechanism: internal CO2 corrosion.",
      href: withQuery(APP_ROUTES.rbi.riskAnalytics, { mechanism: "internal-co2-corrosion" }),
      tone: "orange",
    },
    {
      id: "coverage-gap",
      text: "Inspection coverage gap on produced-water circuits.",
      href: withQuery(APP_ROUTES.inspections.plan, { assetClass: "piping-circuit", fluid: "produced-water" }),
      tone: "blue",
    },
    {
      id: "mitigation",
      text: "Post-mitigation scenario reduces high-risk count from 15 to 11.",
      href: withQuery(APP_ROUTES.rbi.riskAnalytics, { scenario: "full-mitigation" }),
      tone: "cyan",
    },
    {
      id: "psv-evidence",
      text: "6 PSV calibration packages incomplete.",
      href: withQuery(APP_ROUTES.certification.evidencePack, { package: "psv-calibration" }),
      tone: "orange",
    },
    {
      id: "vessel-certificate",
      text: "3 pressure vessels require certificate evidence update.",
      href: withQuery(APP_ROUTES.certification.register, { assetClass: "pressure-vessel", evidence: "update-required" }),
      tone: "red",
    },
  ],
  inspectionValidationSummary: {
    overdue: 19,
    dueWithin90Days: 31,
    current: 52,
    pendingValidation: 22,
    insufficientHistory: 18,
  },
  documentationCompletenessSummary: {
    complete: 91,
    partial: 33,
    missingExpiredUnvalidated: 18,
  },
  topRiskAssets: [
    {
      id: "top-psv-1203",
      assetId: "psv-1203",
      tag: "PSV-1203",
      assetType: "Pressure Safety Device",
      riskScoreBaseline: 24.7,
      riskScoreMitigated: 18.9,
      dominantDamageMechanism: "PSV set-pressure documentation mismatch",
      href: assetRoute("psv-1203"),
    },
    {
      id: "top-v-103",
      assetId: "v-103",
      tag: "V-103 HP Separator",
      assetType: "Pressure Vessel",
      riskScoreBaseline: 21.9,
      riskScoreMitigated: 15.8,
      dominantDamageMechanism: "Internal CO2 corrosion",
      href: assetRoute("v-103"),
    },
    {
      id: "top-tk-301",
      assetId: "tk-301",
      tag: "TK-301 Crude Storage Tank",
      assetType: "Storage Tank",
      riskScoreBaseline: 19.6,
      riskScoreMitigated: 14.2,
      dominantDamageMechanism: "External atmospheric corrosion",
      href: assetRoute("tk-301"),
    },
    {
      id: "top-c-501",
      assetId: "c-501",
      tag: "C-501 Gas Compressor",
      assetType: "Rotating Equipment",
      riskScoreBaseline: 18.3,
      riskScoreMitigated: 13.1,
      dominantDamageMechanism: "Vibration fatigue on compressor discharge piping",
      href: assetRoute("c-501"),
    },
    {
      id: "top-line-6-oil-101",
      assetId: "line-6-oil-101",
      tag: "LINE-6-OIL-101",
      assetType: "Piping Circuit",
      riskScoreBaseline: 16.8,
      riskScoreMitigated: 10.7,
      dominantDamageMechanism: "Erosion-corrosion at high-velocity elbows",
      href: assetRoute("line-6-oil-101"),
    },
  ],
  routePlaceholders: {
    // TODO(route-integration): Replace query placeholder with a dedicated insights list if/when created.
    riskInsights: withQuery(APP_ROUTES.rbi.riskAnalytics, { panel: "risk-insights" }),
    highRiskAssetList: withQuery(APP_ROUTES.rbi.riskRegister, { risk: "high" }),
  },
};
