import type { ProjectFilters, ProjectRecord } from "./project-types";

export const DEFAULT_PROJECT_FILTERS: ProjectFilters = {
  client: "All",
  phase: "All",
  riskProfile: "All",
  search: "",
  site: "All",
  status: "All",
};

export const PROJECTS_DATA: ProjectRecord[] = [
  {
    id: "spm-01",
    code: "SPM-01",
    name: "Instalasi Stasiun Pengumpul Minyak",
    fullFacilityName: "SPM-01 Instalasi Stasiun Pengumpul Minyak - North Block Gathering Station",
    client: "SUCOFINDO",
    site: "North Block Gathering Station",
    facilityType: "Upstream oil and gas gathering station",
    phase: "RBI Baseline",
    riskProfile: "Medium-High",
    status: "Active",
    projectOwner: "SUCOFINDO - Asset Integrity & RBI Services",
    operatingMode: "Continuous 24/7 brownfield operation",
    facilityLife: "Mid-life facility",
    documentation: "Mixed legacy documentation",
    program: "Ongoing RBI baseline implementation",
    campaign: "Active inspection/certification renewal campaign",
    assetCount: 142,
    dataCompleteness: 78,
    rbiProgress: 41,
    issueMetrics: [
      { key: "overdue-inspections", label: "Overdue inspections", value: 19, tone: "red" },
      { key: "open-recommendations", label: "Open recommendations", value: 37, tone: "orange" },
      { key: "active-anomalies", label: "Active anomalies", value: 29, tone: "amber" },
      { key: "overdue-actions", label: "Overdue corrective actions", value: 8, tone: "red" },
      { key: "open-rfis", label: "Open RFIs", value: 14, tone: "cyan" },
      { key: "certificates-due", label: "Certificates due <=180d", value: 11, tone: "amber" },
      { key: "urgent-certificates", label: "Expired/urgent certificates", value: 4, tone: "red" },
      { key: "pending-validation", label: "Pending inspection validation", value: 22, tone: "blue" },
    ],
    throughput: [
      { label: "Gross liquid", value: "22,000 BOPD" },
      { label: "Crude export", value: "16,500 BOPD" },
      { label: "Associated gas", value: "18 MMSCFD" },
      { label: "Produced water", value: "14,000 BWPD" },
      { label: "Onsite storage", value: "6,500 bbl" },
    ],
    assetPopulation: [
      { label: "Pressure vessels", value: 11 },
      { label: "Heater treaters / exchangers", value: 7 },
      { label: "Tanks / sumps / storage", value: 13 },
      { label: "Pumps", value: 22 },
      { label: "Compressors / blowers", value: 5 },
      { label: "Piping circuits / flowlines", value: 31 },
      { label: "Pressure safety devices", value: 17 },
      { label: "Metering / pigging skids", value: 8 },
      { label: "ESD / SDV assemblies", value: 10 },
      { label: "Instrumented / utility packages", value: 18 },
    ],
    riskDistribution: {
      high: 15,
      mediumHigh: 43,
      medium: 56,
      low: 28,
    },
    tags: [
      "V-101 Inlet Separator",
      "CIR-CRUDE-02",
      "PL-601 Crude Export Line",
      "PSV-1203",
      "MTR-801 Custody Metering Skid",
    ],
    issueLabels: [
      "internal CO2 corrosion",
      "corrosion under insulation",
      "MIC in stagnant produced-water lines",
      "PSV set-pressure documentation mismatch",
      "overdue NDT report validation",
    ],
    standards: [
      "API 580-style RBI",
      "API 581-style RBI analytics",
      "API 510-style pressure vessel inspection",
      "API 570-style piping inspection",
      "API 653-style storage tank inspection",
      "ISO 14224-style asset taxonomy and reliability data",
      "inspection certification evidence",
      "SUCOFINDO technical governance",
    ],
  },
  {
    id: "cpp-02",
    code: "CPP-02",
    name: "Central Processing Plant Revamp",
    fullFacilityName: "CPP-02 Central Processing Plant Revamp - East Trunk Processing Hub",
    client: "Pertamina Hulu Energi",
    site: "East Trunk Processing Hub",
    facilityType: "Central processing plant",
    phase: "Revamp Readiness",
    riskProfile: "Medium",
    status: "Monitoring",
    projectOwner: "SUCOFINDO - EPC Integrity Assurance",
    operatingMode: "Brownfield revamp with phased shutdown windows",
    facilityLife: "Late-life facility entering targeted revamp",
    documentation: "Controlled revamp dossier with legacy tie-ins",
    program: "Pre-revamp AIM readiness and asset taxonomy clean-up",
    campaign: "Piping class reconciliation and package validation",
    assetCount: 218,
    dataCompleteness: 84,
    rbiProgress: 24,
    issueMetrics: [
      { key: "overdue-inspections", label: "Overdue inspections", value: 12, tone: "orange" },
      { key: "open-recommendations", label: "Open recommendations", value: 28, tone: "amber" },
      { key: "active-anomalies", label: "Active anomalies", value: 17, tone: "amber" },
      { key: "overdue-actions", label: "Overdue corrective actions", value: 5, tone: "orange" },
      { key: "open-rfis", label: "Open RFIs", value: 9, tone: "cyan" },
      { key: "certificates-due", label: "Certificates due <=180d", value: 16, tone: "amber" },
      { key: "urgent-certificates", label: "Expired/urgent certificates", value: 2, tone: "red" },
      { key: "pending-validation", label: "Pending inspection validation", value: 18, tone: "blue" },
    ],
    throughput: [
      { label: "Liquid handling", value: "41,000 BOPD" },
      { label: "Gas handling", value: "42 MMSCFD" },
      { label: "Water treating", value: "24,000 BWPD" },
      { label: "Revamp packages", value: "9 trains" },
    ],
    assetPopulation: [
      { label: "Pressure vessels", value: 24 },
      { label: "Heat transfer equipment", value: 18 },
      { label: "Storage tanks", value: 22 },
      { label: "Pumps", value: 38 },
      { label: "Compressors", value: 11 },
      { label: "Piping circuits", value: 62 },
      { label: "PSVs", value: 30 },
      { label: "Skids / packages", value: 13 },
    ],
    riskDistribution: {
      high: 12,
      mediumHigh: 51,
      medium: 94,
      low: 61,
    },
    tags: ["HE-202 Heat Exchanger", "P-201A/B Crude Transfer Pumps", "CIR-GAS-01", "PSV-1204"],
    issueLabels: ["localized pitting", "incomplete P&ID revision control", "flange leakage"],
    standards: ["API 570-style piping inspection", "document control", "audit trail", "regulatory matrix"],
  },
  {
    id: "ggs-07",
    code: "GGS-07",
    name: "South Gathering Booster Station",
    fullFacilityName: "GGS-07 South Gathering Booster Station - South Cluster Compression Hub",
    client: "Medco E&P",
    site: "South Cluster Compression Hub",
    facilityType: "Gathering and booster station",
    phase: "Inspection Campaign",
    riskProfile: "Medium-High",
    status: "At Risk",
    projectOwner: "SUCOFINDO - Field Integrity Delivery",
    operatingMode: "Continuous booster service with rotating equipment constraints",
    facilityLife: "Mid-life facility with deferred inspection backlog",
    documentation: "Partial inspection history and mixed vendor packages",
    program: "Backlog recovery and rotating equipment integrity review",
    campaign: "Compressor discharge piping vibration fatigue review",
    assetCount: 96,
    dataCompleteness: 69,
    rbiProgress: 33,
    issueMetrics: [
      { key: "overdue-inspections", label: "Overdue inspections", value: 21, tone: "red" },
      { key: "open-recommendations", label: "Open recommendations", value: 31, tone: "orange" },
      { key: "active-anomalies", label: "Active anomalies", value: 24, tone: "orange" },
      { key: "overdue-actions", label: "Overdue corrective actions", value: 11, tone: "red" },
      { key: "open-rfis", label: "Open RFIs", value: 7, tone: "cyan" },
      { key: "certificates-due", label: "Certificates due <=180d", value: 8, tone: "amber" },
      { key: "urgent-certificates", label: "Expired/urgent certificates", value: 3, tone: "red" },
      { key: "pending-validation", label: "Pending inspection validation", value: 15, tone: "blue" },
    ],
    throughput: [
      { label: "Liquid handling", value: "14,500 BOPD" },
      { label: "Gas boost", value: "26 MMSCFD" },
      { label: "Produced water", value: "9,200 BWPD" },
      { label: "Compression trains", value: "3 active" },
    ],
    assetPopulation: [
      { label: "Pressure vessels", value: 9 },
      { label: "Scrubbers / KO drums", value: 8 },
      { label: "Pumps", value: 16 },
      { label: "Compressors", value: 7 },
      { label: "Piping circuits", value: 29 },
      { label: "PSVs", value: 15 },
      { label: "ESD / SDV assemblies", value: 12 },
    ],
    riskDistribution: {
      high: 18,
      mediumHigh: 31,
      medium: 32,
      low: 15,
    },
    tags: ["C-501 Gas Compressor", "C-502 Vapor Recovery Compressor", "V-110 Gas Scrubber", "SDV-701"],
    issueLabels: ["vibration fatigue on compressor discharge piping", "gasket degradation", "external atmospheric corrosion"],
    standards: ["API 580-style RBI", "MOC/IOW trigger review", "inspection certification evidence"],
  },
  {
    id: "whp-03",
    code: "WHP-03",
    name: "Offshore Wellhead Platform Integrity Review",
    fullFacilityName: "WHP-03 Offshore Wellhead Platform Integrity Review - North Sea Satellite Platform",
    client: "Premier Oil",
    site: "North Sea Satellite Platform",
    facilityType: "Offshore wellhead platform",
    phase: "Integrity Review",
    riskProfile: "High",
    status: "Active",
    projectOwner: "SUCOFINDO - Offshore Integrity Cell",
    operatingMode: "Normally attended offshore production platform",
    facilityLife: "Late-life offshore facility",
    documentation: "Legacy offshore dossier with recent survey supplements",
    program: "Offshore integrity assurance and corrosion management review",
    campaign: "Topside pressure system and isolation valve evidence campaign",
    assetCount: 74,
    dataCompleteness: 72,
    rbiProgress: 52,
    issueMetrics: [
      { key: "overdue-inspections", label: "Overdue inspections", value: 9, tone: "orange" },
      { key: "open-recommendations", label: "Open recommendations", value: 24, tone: "orange" },
      { key: "active-anomalies", label: "Active anomalies", value: 19, tone: "orange" },
      { key: "overdue-actions", label: "Overdue corrective actions", value: 6, tone: "red" },
      { key: "open-rfis", label: "Open RFIs", value: 12, tone: "cyan" },
      { key: "certificates-due", label: "Certificates due <=180d", value: 6, tone: "amber" },
      { key: "urgent-certificates", label: "Expired/urgent certificates", value: 1, tone: "red" },
      { key: "pending-validation", label: "Pending inspection validation", value: 11, tone: "blue" },
    ],
    throughput: [
      { label: "Oil export", value: "8,400 BOPD" },
      { label: "Gas lift", value: "12 MMSCFD" },
      { label: "Water handling", value: "5,800 BWPD" },
      { label: "Wells tied-in", value: "11 slots" },
    ],
    assetPopulation: [
      { label: "Pressure vessels", value: 7 },
      { label: "Wellhead packages", value: 13 },
      { label: "Piping circuits", value: 25 },
      { label: "PSVs", value: 10 },
      { label: "Critical valves", value: 12 },
      { label: "Utility packages", value: 7 },
    ],
    riskDistribution: {
      high: 20,
      mediumHigh: 26,
      medium: 21,
      low: 7,
    },
    tags: ["ESDV-702", "LINE-6-OIL-101", "V-115 KO Drum", "PSV-1203"],
    issueLabels: ["H2S-related susceptibility screening", "nozzle coating breakdown", "corrosion under insulation"],
    standards: ["API 510-style pressure vessel inspection", "API 570-style piping inspection", "audit trail"],
  },
  {
    id: "tkf-11",
    code: "TKF-11",
    name: "Tank Farm Certification Recovery",
    fullFacilityName: "TKF-11 Tank Farm Certification Recovery - Coastal Storage Terminal",
    client: "PGN Saka",
    site: "Coastal Storage Terminal",
    facilityType: "Tank farm and terminal storage",
    phase: "Certification Recovery",
    riskProfile: "Medium",
    status: "Planned",
    projectOwner: "SUCOFINDO - Certification Recovery Team",
    operatingMode: "Terminal storage with planned external inspection windows",
    facilityLife: "Mature storage terminal",
    documentation: "Certificate recovery dossier and tank inspection backlog",
    program: "API 653-style storage tank evidence recovery",
    campaign: "Tank shell, roof, bunding, and calibration evidence close-out",
    assetCount: 63,
    dataCompleteness: 61,
    rbiProgress: 18,
    issueMetrics: [
      { key: "overdue-inspections", label: "Overdue inspections", value: 7, tone: "orange" },
      { key: "open-recommendations", label: "Open recommendations", value: 18, tone: "amber" },
      { key: "active-anomalies", label: "Active anomalies", value: 12, tone: "amber" },
      { key: "overdue-actions", label: "Overdue corrective actions", value: 4, tone: "orange" },
      { key: "open-rfis", label: "Open RFIs", value: 10, tone: "cyan" },
      { key: "certificates-due", label: "Certificates due <=180d", value: 13, tone: "amber" },
      { key: "urgent-certificates", label: "Expired/urgent certificates", value: 5, tone: "red" },
      { key: "pending-validation", label: "Pending inspection validation", value: 16, tone: "blue" },
    ],
    throughput: [
      { label: "Tank storage", value: "120,000 bbl" },
      { label: "Truck loading", value: "180 trucks/day" },
      { label: "Water drain", value: "3,500 BWPD" },
      { label: "Active tanks", value: "14 tanks" },
    ],
    assetPopulation: [
      { label: "Storage tanks", value: 28 },
      { label: "Transfer pumps", value: 11 },
      { label: "Piping circuits", value: 14 },
      { label: "PSVs / vents", value: 4 },
      { label: "Metering skids", value: 3 },
      { label: "Firewater packages", value: 3 },
    ],
    riskDistribution: {
      high: 6,
      mediumHigh: 14,
      medium: 25,
      low: 18,
    },
    tags: ["TK-301 Crude Storage Tank", "TK-302 Produced Water Tank", "TK-303 Diesel Tank", "P-205A/B Produced Water Pumps"],
    issueLabels: ["expired inspection certificate", "missing calibration evidence", "external atmospheric corrosion"],
    standards: ["API 653-style storage tank inspection", "regulatory matrix", "document control"],
  },
];
